---
title: "Clustering differences"
author: "Will A. S. Hardy"
date: "27/01/2021"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
library(tidyverse)
library(tsibble)
library(tidyLPA)
library(future)
library(furrr)
library(tidymodels)
library(workflows)
library(tune)

knitr::opts_chunk$set(echo = TRUE)

set.seed(32)

gp <- 
  read_rds("../OneDrive/2_interimdata/8_linkeddata/gp_agesex_qof_combined.rds") %>% 
  mutate(npat = N,
         N = NULL,
         practice_id = as_factor(practiceid),
         dispensing = as_factor(dispensing),
         hboard = as_factor(hboard)) %>% 
  ungroup() %>% 
  janitor::clean_names()

differences_files <- 
  list.files("../data/differences/")
names(differences_files) <- 
  str_remove_all(differences_files, "_discreps.rds")

differences <- 
  map_dfr(.x = differences_files,
          .f = ~read_rds(paste0("../data/differences/", .x)),
          .id = "drug") %>% 
  mutate(drug = as_factor(drug)) %>% 
  select(drug, regional_unit, datename, discrepancy)

```


## Data cleaning

```{r, data-problem-values, warning=FALSE}
differences %>% 
  pivot_wider(names_from = datename, values_from = discrepancy) %>% 
  psych::describeBy(group = "drug", fast = TRUE)
```

* Problem with `oac` data

```{r, data-which-problem}
differences %>% 
  filter(drug == "oac" & 
           (is.na(discrepancy) | is.nan(discrepancy) | is.infinite(discrepancy))) %>% 
  group_by(datename) %>% 
  count()

differences %>% 
  filter(drug == "oac" & 
           (is.na(discrepancy) | is.nan(discrepancy) | is.infinite(discrepancy))) %>% 
  group_by(drug, regional_unit) %>% 
  count()
```

* Missing/inappropriate data in five practices (all in covid months)
* Removed these practices from the `oac` data

```{r, data-cleaning}
differences <- 
  differences %>% 
  anti_join(y = differences %>% 
              filter(drug == "oac" & 
                       (is.na(discrepancy) |
                          is.nan(discrepancy) | 
                          is.infinite(discrepancy))) %>% 
              group_by(drug, regional_unit) %>% 
              count(), 
            by = c("drug", "regional_unit"))
```


## k-means

### Elbow plots

```{r, k-means-elbow}
differences %>% 
  pivot_wider(names_from = datename, values_from = discrepancy) %>% 
  nest_by(drug) %>% 
  mutate(k_means = list(map(.x = 1:10, 
                           .f = ~kmeans(x = data[2:7], centers = .x, 
                                        nstart = 5, iter.max = 50)))) %>% 
  mutate(tot_within_ss = list(map_dbl(k_means, "tot.withinss")), 
         clusters = list(map(k_means, "cluster")),
         n_clusters = list(map_dbl(clusters, max))) %>% 
  summarise(tot_within_ss = tot_within_ss,
            n_clusters = n_clusters) %>% 
  ggplot(aes(x = n_clusters, y = tot_within_ss)) +
  geom_line() +
  facet_wrap(~drug, scales = "free") +
  scale_x_continuous(breaks = seq(0, 10, by = 2))
```

* Visual inspections of elbow plots WH 2021-01-27
  * ace 3
  * adreno 3
  * azithro 3
  * contra 3
  * cortico 4
  * hcq 4
  * nsaid 3
  * oac 3
  * paracet 4
  * vitd 4
  

```{r, k-means-summary-plots}
drugs <- unique(as.character(differences$drug))
n_cluster <- c(3,3,3,3,4,4,3,3,4,4)

differences_wide <- 
  differences %>% 
  pivot_wider(names_from = datename, values_from = discrepancy)

best_k_means_fits <- 
  map2(.x = drugs,
       .y = n_cluster,
       .f = ~kmeans(x = filter(differences_wide, drug == .x)[3:8],
                    centers = .y,
                    nstart = 5, iter.max = 50))

best_k_means_fits %>%
  set_names(nm = drugs) %>% 
  transpose() %>% 
  pluck("size") %>% 
    modify_depth(.depth = 1, 
               .f = ~rownames_to_column(.data = as.data.frame(.), 
                                        var = "cluster")) %>% 
  bind_rows(.id = "drug") %>% 
  rename(.data = ., n = `.`) %>% 
  pivot_wider(names_from = cluster, values_from = n) %>% 
  knitr::kable()


best_k_means_fits %>%
  set_names(nm = drugs) %>% 
  transpose() %>% 
  pluck("centers") %>% 
  modify_depth(.depth = 1, 
               .f = ~rownames_to_column(.data = as.data.frame(.), 
                                        var = "cluster")) %>% 
  bind_rows(.id = "drug") %>% 
  pivot_longer(cols = `2020 Mar`:`2020 Aug`,
               names_to = "datename", values_to = "discrepancy") %>% 
  mutate(datename = yearmonth(datename)) %>% 
  ggplot(aes(x = datename, 
             y = discrepancy,
             group = as.factor(cluster),
             colour = as.factor(cluster))) + 
  geom_line() +
  facet_wrap(~drug, scales = "free") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# best_k_means_fits %>% 
#   set_names(drugs) %>% 
#   transpose() %>%
#   pluck("cluster")

```


## Latent profile analysis

```{r, lpa-models-nested, include=FALSE}
tictoc::tic()
lpa_analysis <- 
  differences_wide %>% 
  anti_join(y = differences_wide %>% # These cause computation issues. Look at separately.
              filter(drug == "ace" & `2020 Jul` < -50), 
            by = c("drug", "regional_unit")) %>% 
  
  nest_by(drug) %>% 
  mutate(lpa_models = 
           list(estimate_profiles(df = data,
                                  select_vars = c("2020 Mar", "2020 Apr", 
                                                  "2020 May", "2020 Jun", 
                                                  "2020 Jul", "2020 Aug"),
                                  n_profiles = 1:8, 
                                  models = c(1:3))),
         lpa_fits = 
           list(compare_solutions(lpa_models, 
                                  statistics = c("BIC", "AIC", "SABIC", "BLRT_p",
                                                 "prob_min", "Entropy"))),
         lpa_plots = list(plot_profiles(lpa_models, 
                                        rawdata = FALSE, 
                                        sd = FALSE)),
         best_lpa_rn = as.numeric(list(lpa_fits$AHP)),
         best_lpa_fit = list(lpa_fits$fits[lpa_fits$AHP,]),
         best_lpa_model = flatten(list(lpa_models[lpa_fits$AHP])),
         best_lpa_data = list(get_data(best_lpa_model)),
         classes = list(flatten(flatten(list(lpa_models[lpa_fits$AHP])))$model$classification),
         class_count = list(table(flatten(flatten(list(lpa_models[lpa_fits$AHP])))$model$classification)),
         lpa_class = list(bind_cols(drug = drug, 
                                    regional_unit = data$regional_unit, 
                                    lpa_class = classes)))
tictoc::toc()
```

```{r, lpa-best-model-plot, include=FALSE}
lpa_analysis <- 
  lpa_analysis %>% 
  mutate(best_lpa_model_plot = list(plot_profiles(best_lpa_model, 
                                                  rawdata = FALSE, 
                                                  sd = FALSE)),
         best_lpa_model_plot_lab = list(best_lpa_model_plot + 
                                          labs(title = drug)),
         best_lpa_cprob = list(select(best_lpa_model$dff,
                                      starts_with("CPROB"), Class)))

lpa_analysis %>% 
  pluck("best_lpa_cprob") %>% 
  set_names(drugs)

```

```{r, lpa-best-model-plot-2}
lpa_analysis$lpa_fits

lpa_analysis %>% 
  pluck("class_count") %>% 
  set_names(drugs) %>% 
  bind_rows(.id = "drug")

```


```{r}
lpa_analysis$lpa_fits %>% 
  set_names(drugs) %>% 
  pluck("cortico")

lpa_analysis$lpa_models %>% 
  set_names(drugs) %>% 
  pluck("cortico")

lpa_analysis$lpa_models %>% 
  set_names(drugs) %>% 
  pluck("cortico") %>% 
  pluck("model_2_class_6") %>% 
  plot_profiles(rawdata = FALSE, sd = FALSE)
```

```{r}
lpa_analysis$lpa_fits %>% 
  set_names(drugs) %>% 
  pluck("oac")

lpa_analysis$lpa_models %>% 
  set_names(drugs) %>% 
  pluck("oac")

lpa_analysis$lpa_models %>% 
  set_names(drugs) %>% 
  pluck("oac") %>% 
  pluck("model_2_class_6") %>% 
  plot_profiles(rawdata = FALSE, sd = FALSE)
```


```{r, lpa-best-model-class-assignment}
lpa_analysis %>% 
  pluck("lpa_class") %>% 
  bind_rows() %>% 
  pivot_wider(names_from = drug, names_prefix = "lpa_class_",
              values_from = lpa_class)

lpa_analysis %>% 
  pluck("lpa_class") %>% 
  bind_rows() %>% 
  pivot_wider(names_from = drug, names_prefix = "lpa_class_",
              values_from = lpa_class) %>% 
  psych::describe()

```


### Outliers

```{r, lpa-models, eval=FALSE}
drugs <- unique(as.character(differences$drug))

differences_wide <- 
  differences %>% 
  pivot_wider(names_from = datename, values_from = discrepancy)

system.time(differences_wide %>% 
              filter(drug == "oac") %>% 
              ungroup() %>% 
              select(`2020 Mar`:`2020 Aug`) %>% 
              estimate_profiles(df = ., n_profiles = 1:5, models = c(1:3, 6)))

lpaProfiles <- function(data, filter){
  data %>% 
    filter(drug == filter) %>% 
    ungroup() %>% 
    select(`2020 Mar`:`2020 Aug`) %>% 
    estimate_profiles(df = ., n_profiles = 1:5, models = c(1:3, 6))
}

plan(cluster)
system.time(lpa_fits <- 
              future_map(.x = drugs,
                         .f = ~lpaProfiles(differences_wide, .x)))
plan(sequential)

lpa_fits %>% 
  saveRDS("../data/models/lpa_fits.rds")
```


```{r, seperate-lpa-models, eval=FALSE}
lpaProfiles <- function(data, filter){
  data %>% 
    filter(drug == filter) %>% 
    ungroup() %>% 
    select(`2020 Mar`:`2020 Aug`) %>% 
    estimate_profiles(df = ., n_profiles = 1:6, models = c(1:3, 6))
}

tictoc::tic()
system.time(oac_lpa <- lpaProfiles(differences_wide, "oac"))
print("step 1")
print("step 2")
system.time(azithro_lpa <- lpaProfiles(differences_wide, "azithro"))
print("step 3")
system.time(contra_lpa <- lpaProfiles(differences_wide, "contra"))
print("step 4")
system.time(cortico_lpa <- lpaProfiles(differences_wide, "cortico"))
print("step 5")
system.time(hcq_lpa <- lpaProfiles(differences_wide, "hcq"))
print("step 6")
system.time(nsaid_lpa <- lpaProfiles(differences_wide, "nsaid"))
print("step 7")
system.time(vitd_lpa <- lpaProfiles(differences_wide, "vitd"))
print("step 8")
system.time(paracet_lpa <- lpaProfiles(differences_wide, "paracet"))
print("step 9")
#system.time(adreno_lpa <- lpaProfiles(differences_wide, "adreno"))
system.time(ace_lpa <- differences_wide %>%
              filter(drug == "ace") %>% 
              filter(`2020 Jul` > -50) %>% # Outliers causing computation problems
              estimate_profiles(df = .[3:8], 
                                n_profiles = 1:6, 
                                models = c(1:3, 6)))
print("step 10")
lpa_sep_fits <- list(ace_lpa, azithro_lpa, contra_lpa, cortico_lpa, 
                     hcq_lpa, nsaid_lpa, oac_lpa, paracet_lpa, vitd_lpa)
tictoc::toc()


```


```{r, adreno-lpa, eval=FALSE}
system.time(differences_wide %>% 
              filter(drug == "adreno") %>% 
              # filter(`2020 Jul` > -50) %>% # Outliers causing computation problems
              estimate_profiles(df = .[c(3:8)], 
                                n_profiles = 1:5, 
                                models = c(1:3,6)) %>% 
              plot_profiles(rawdata = FALSE))

## Models 1:3
# 2708.712 secs with df = .[c(3:5)]
# 63.237 secs with df = .[c(3:6)]
# 1101.290 secs with df = .[c(3:7)]
# 1618.723 secs with df = .[c(3:8)]
## Models 1:3, 6
# 2338.966 secs with df = .[c(3:8)]

differences_wide %>% 
  filter(drug == "adreno") %>% 
  ggplot(aes(x = `2020 May`)) +
  geom_histogram()
```


## Logistic regression

### LPA profiles

```{r}
lpa_analysis %>% 
  pluck("lpa_class") %>% 
  bind_rows() %>% 
  mutate(lpa_class = as_factor(lpa_class)) %>% 
  left_join(filter(gp, year == 2020), by = c("regional_unit" = "practice_id")) %>% 
  select(drug, regional_unit, lpa_class, ngp, dispensing, where(is.numeric)) %>% 
  select(-c(easting, northing, regional_unit, year)) %>% 
  nest_by(drug) %>% 
  mutate(mod = list(glm(lpa_class ~ ., data = data, family = "binomial"))) %>% 
  summarise(broom::glance(mod), 
            list(summary(mod))) %>% 
  pluck("list(summary(mod))") %>% 
  set_names(drugs)
  
```


## Tidymodels

### LPA profiles

```{r, preparing-tidymodels-data}
diff_data <- 
  lpa_analysis %>% 
  pluck("lpa_class") %>% 
  bind_rows() %>% 
  mutate(lpa_class = as_factor(lpa_class)) %>% 
  left_join(filter(gp, year == 2020), by = c("regional_unit" = "practice_id")) %>% 
  select(drug, regional_unit, lpa_class, ngp, dispensing, where(is.numeric)) %>% 
  select(-c(easting, northing, regional_unit, year)) %>% 
  filter(drug == "ace") %>% 
  mutate(lpa_class = as.factor(as.numeric(lpa_class)))


diff_data_split <- 
  diff_data %>% 
  initial_split(prop = 2/3)

diff_data_train <- training(diff_data_split)
diff_data_test <- testing(diff_data_split)
diff_data_cv <- vfold_cv(diff_data_train)

diff_data_train %>% 
  write_csv("../data/weka/ace_train.csv")
diff_data_test %>% 
  write_csv("../data/weka/ace_test.csv")

```



```{r}
diff_recipe <- 
  recipe(lpa_class ~ ., data = select(ungroup(diff_data_train), -drug)) %>% 
  step_normalize(all_numeric())
```


```{r}
lr_model <- 
  # specify that the model is a random forest
  logistic_reg() %>%
  # select the engine/package that underlies the model
  set_engine("glm") %>%
  # choose either the continuous regression or binary classification mode
  set_mode("classification") 

rf_model <- 
  # specify that the model is a random forest
  rand_forest() %>%
  # specify that the `mtry` parameter needs to be tuned
  set_args(mtry = tune(), trees = tune()) %>%
  # select the engine/package that underlies the model
  set_engine("ranger", importance = "impurity") %>%
  # choose either the continuous regression or binary classification mode
  set_mode("classification") 
```



```{r}
lr_workflow <- 
  workflow() %>% 
  add_recipe(diff_recipe) %>% 
  add_model(lr_model)

rf_workflow <- workflow() %>%
  # add the recipe
  add_recipe(diff_recipe) %>%
  # add the model
  add_model(rf_model)
```


```{r}
rf_grid <- expand.grid(mtry = c(3,4,5), trees = c(100, 500))
rf_tune_results <- 
  rf_workflow %>% 
  tune_grid(resamples = diff_data_cv,
            grid = rf_grid,
            metrics = metric_set(accuracy, roc_auc, spec, sens))

rf_tune_results %>% 
  collect_metrics()

lr_grid <- expand.grid(mtry = c(3,4,5))
lr_tune_results <- 
  lr_workflow %>% 
  tune_grid(resamples = diff_data_cv,
            metrics = metric_set(accuracy, roc_auc, spec, sens))

lr_tune_results %>% 
  collect_metrics()

```

