---
title: "Hydroxychloroquine sulphate"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup}
## Packages
devtools::install_github("https://github.com/w-hardy/serCymruTools")
library(tidyverse)
library(lubridate)
library(tsibble)
library(rstan) # needed to load prophet
library(prophet)
library(fable)
library(fable.prophet)
library(feasts)
library(furrr)
library(rebus)
library(MplusAutomation)
library(tidyLPA)
library(serCymruTools)

## Options
knitr::opts_chunk$set(cache = TRUE)
options(mc.cores = parallel::detectCores() - 1)
rstan_options(auto_write = TRUE)


## Seed
set.seed(32)

```


```{r}
gp <- 
  read_rds("../OneDrive/2_interimdata/8_linkeddata/gp_agesex_qof_combined.rds") %>%
  mutate(npat = N,
         N = NULL, 
         practice_id = practiceid) %>% 
  filter(year == 2020) # do something better
gp$practiceid = NULL

adreno <- read_rds("../data/presdata_updates_040121/presc_wales_adrenoceptor-agonists.rds") %>% 
  mutate(datename = dmy(paste0("28-", datename))) %>% 
  janitor::clean_names()


## Sort into monthly count data
adreno_monthly_count <- adreno %>% 
  group_by(datename) %>% 
  summarise(n = sum(quantity)) %>% 
  mutate(datename = yearmonth(datename),
         n = case_when(str_detect(datename, pattern = "Jan") ~ n/31,
                       str_detect(datename, pattern = "Feb") ~ n/28.25,
                       str_detect(datename, pattern = "Mar") ~ n/31,
                       str_detect(datename, pattern = "Apr") ~ n/30,
                       str_detect(datename, pattern = "May") ~ n/31,
                       str_detect(datename, pattern = "Jun") ~ n/30,
                       str_detect(datename, pattern = "Jul") ~ n/31,
                       str_detect(datename, pattern = "Aug") ~ n/31,
                       str_detect(datename, pattern = "Sep") ~ n/30,
                       str_detect(datename, pattern = "Oct") ~ n/31,
                       str_detect(datename, pattern = "Nov") ~ n/30,
                       str_detect(datename, pattern = "Dec") ~ n/31)) %>% 
  ungroup() %>% 
  as_tsibble(index = datename)


adreno_monthly_quantity_hb <- 
  right_join(adreno, select(gp, c(practice_id, hboard)), 
             by = c("practice_id")) %>%
  countRegional(hboard, datename, quantity) %>% 
  left_join(gp %>% 
              select(c(practice_id, npat, hboard)) %>% 
              group_by(hboard) %>% 
              summarise(npat = sum(npat)), by = c("regional_unit" = "hboard")) %>% 
  mutate(n = 1000*n/npat) # quantity per 1000 pts

adreno_monthly_quantity_cluster <- 
  right_join(adreno, select(gp, c(practice_id, cluster)), 
             by = c("practice_id")) %>%
  countRegional(cluster, datename, quantity) %>% 
  left_join(gp %>% 
  select(c(practice_id, npat, cluster)) %>% 
  group_by(cluster) %>% 
  summarise(npat = sum(npat)), by = c("regional_unit" = "cluster")) %>% 
  mutate(n = 1000*n/npat) # quantity per 1000 pts

adreno_monthly_quantity_gp <- 
  countRegional(adreno, practice_id, datename, quantity) %>% 
  right_join(select(gp, c(practice_id, npat)), 
            by = c("regional_unit" = "practice_id")) %>% 
  mutate(n = 1000*n/npat)
  

## Sort into monthly count data pre-lockdown (2020-03-23)
adreno_monthly_count_pre_cv19 <- 
  adreno_monthly_count %>% 
  filter(datename < dmy("01-03-2020"))

adreno_monthly_quantity_hb_pre_cv19 <- 
  adreno_monthly_quantity_hb %>% 
    filter(datename < dmy("01-03-2020"))

adreno_monthly_quantity_cluster_pre_cv19 <- 
  adreno_monthly_quantity_cluster %>% 
    filter(datename < dmy("01-03-2020"))

adreno_monthly_quantity_gp_pre_cv19 <- 
  adreno_monthly_quantity_gp %>% 
    filter(datename < dmy("01-03-2020"))


```


## Overview

### 2016-2020 plot of all adreno prescriptions 

```{r adreno-monthly-ts-plot, fig.cap="Total quantity of adrenoreceptor agonists prescribed per month."}
adreno %>% 
  group_by(datename) %>% 
  summarise(n = sum(quantity)) %>% 
  tsibble() %>% 
  autoplot(n) +
  geom_vline(xintercept = dmy("23-March-2020"), colour = "red") # add line to mark the start of lockdown
```

* 

### Seasonality

```{r adreno-monthly-seasonality-plot}
df <- adreno_monthly_count_pre_cv19 %>% 
  mutate(month = as.factor(month(datename, label = TRUE, abbr = TRUE)),
         year = as.factor(year(datename))) 

df2 <- df %>% 
  as_tibble() %>% 
  filter(year(datename) != 2020) %>% 
  group_by(month) %>% 
  summarise(n = mean(n))

df %>% 
  ggplot(aes(x = month, y = n, colour = year, group = year)) +
  geom_line() +
  geom_line(data = df2, aes(x = month, y = n, group = "Avg"), 
            colour = "red", lty = 2) +
  labs(caption = "Red dashed line is mean for 2016-2019")

```
*


```{r}
adreno_monthly_count_pre_cv19 %>% 
  mutate(datename = yearmonth(datename)) %>% 
  gg_subseries(y = n, period = "year")
```

* 

### Lag plots

```{r}
adreno_monthly_count_pre_cv19 %>%
  mutate(datename = yearmonth(datename)) %>% 
  gg_lag(y = n, geom = "point", lags = 1:12)
```

```{r}
adreno_monthly_count_pre_cv19 %>% 
  mutate(datename = yearmonth(datename)) %>% 
  gg_lag(y = n, geom = "point", lags = 13:24)
```
*


### Autocorrelation

```{r}
tseries::adf.test(adreno_monthly_count$n)
urca::ur.df(adreno_monthly_count$n)
```


```{r}
adreno_monthly_count_pre_cv19 %>%
  mutate(datename = yearmonth(datename)) %>% 
  ACF(n, lag_max = 60) %>% autoplot()
```

* Autocorrelation greatest at 2 and 12

```{r}
adreno_monthly_count_pre_cv19$n %>%
  pacf(lag.max = 60)
```


## Overview of each drug

```{r}
adreno %>% 
  group_by(datename, chemname) %>% 
  summarise(n = sum(quantity)) %>% 
  mutate(n = case_when(str_detect(datename, pattern = "-01-") ~ n/31,
                       str_detect(datename, pattern = "-02-") ~ n/28.25,
                       str_detect(datename, pattern = "-03-") ~ n/31,
                       str_detect(datename, pattern = "-04-") ~ n/30,
                       str_detect(datename, pattern = "-05-") ~ n/31,
                       str_detect(datename, pattern = "-06-") ~ n/30,
                       str_detect(datename, pattern = "-07-") ~ n/31,
                       str_detect(datename, pattern = "-08-") ~ n/31,
                       str_detect(datename, pattern = "-09-") ~ n/30,
                       str_detect(datename, pattern = "-10-") ~ n/31,
                       str_detect(datename, pattern = "-11-") ~ n/30,
                       str_detect(datename, pattern = "-12-") ~ n/31))%>% 
  as_tsibble(index = datename, key = chemname) %>% 
  autoplot(n) +
  theme(legend.position = "none") +
  geom_vline(xintercept = dmy("23-March-2020"), colour = "red") # add line to mark the start of lockdown
```

## Time series components

```{r}
dcmp <- 
  adreno_monthly_count_pre_cv19 %>% 
  mutate(datename = yearmonth(datename)) %>% 
  model(STL(n))

adreno_monthly_count_pre_cv19 %>% 
  mutate(datename = yearmonth(datename)) %>% 
  autoplot(n, color = "grey") + 
  autolayer(components(dcmp), trend, color = "red")

components(dcmp) %>% 
  autoplot()
```

```{r}
adreno_monthly_count %>% 
  mutate(datename = yearmonth(datename)) %>% 
  autoplot(n, color = "grey") + 
  autolayer(components(dcmp), season_adjust, colour = "blue") +
  labs(title = "Seasonally adjusted")
```


## Modelling

### By Health Board

```{r, health-board-modelling}
plan(multisession)
system.time(adreno_hb_cv_models <-
  regionalCV(data = adreno_monthly_quantity_hb_pre_cv19))
plan(sequential)

adreno_hb_cv_models %>%
  saveRDS("../data/adreno_hb_cv_models.rds")

adreno_hb_cv_models <- 
  read_rds("../data/adreno_hb_cv_models.rds")

adreno_hb_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  ggplot(aes(x = MAPE)) +
  geom_histogram()

adreno_hb_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  group_by(.model) %>% 
  count() %>% 
  arrange(desc(n))

adreno_hb_cv_models %>% 
  group_by(regional_unit) %>% 
  ggplot(aes(x = reorder(.model, MAPE, mean), y = MAPE)) + # reorder by mean of y
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90))
```

* 756.556 seconds 2021-01-12

```{r}
plan(cluster)
system.time(adreno_hb_fcsts <- regionalJointFcsts(adreno_monthly_quantity_hb_pre_cv19))
plan(sequential)

adreno_hb_fcsts %>%
  saveRDS("../data/adreno_hb_fcsts.rds")

adreno_hb_fcsts <- 
  read_rds("../data/adreno_hb_fcsts.rds")
```

* 

### By GP Cluster

```{r, gp-cluster-modelling}
plan(multisession)
system.time(adreno_gp_cluster_cv_models <-
  regionalCV(data = adreno_monthly_quantity_cluster_pre_cv19))
plan(sequential)

adreno_gp_cluster_cv_models %>%
  saveRDS("../data/adreno_gp_cluster_cv_models.rds")

adreno_gp_cluster_cv_models <- 
  read_rds("../data/adreno_gp_cluster_cv_models.rds")

adreno_gp_cluster_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  ggplot(aes(x = MAPE)) +
  geom_histogram()

adreno_gp_cluster_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  group_by(.model) %>% 
  count() %>% 
  arrange(desc(n))

adreno_gp_cluster_cv_models %>% 
  group_by(regional_unit) %>% 
  ggplot(aes(x = reorder(.model, MAPE, mean), y = MAPE)) + # reorder by mean of y
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90))


```

* 

```{r}
plan(multisession)
system.time(adreno_gp_cluster_fcsts <-
              regionalJointFcsts(adreno_monthly_quantity_cluster_pre_cv19))
plan(sequential)

adreno_gp_cluster_fcsts %>%
  saveRDS("../data/adreno_gp_cluster_fcsts.rds")

adreno_gp_cluster_fcsts <- 
  read_rds("../data/adreno_gp_cluster_fcsts.rds")
```

* 

### By Practice

```{r, gp-practice-modelling}
complete_gp <- 
  adreno_monthly_quantity_gp_pre_cv19 %>% 
  as_tibble() %>% 
  group_by(regional_unit) %>% 
  count() %>% 
  filter(n >= 62) %>% 
  .$regional_unit %>% 
  unique()


plan(cluster)
# Chunking analyses into ~100 GPs uses ~ 23Gb of RAM
system.time(adreno_gp_cv_models_1 <-
  adreno_monthly_quantity_gp_pre_cv19 %>%
    filter(regional_unit %in% complete_gp[1:100]) %>%
              regionalCV(init = 48))
system.time(adreno_gp_cv_models_2 <-
  adreno_monthly_quantity_gp_pre_cv19 %>%
    filter(regional_unit %in% complete_gp[101:200]) %>%
              regionalCV(init = 48))
system.time(adreno_gp_cv_models_3 <-
  adreno_monthly_quantity_gp_pre_cv19 %>%
    filter(regional_unit %in% complete_gp[201:300]) %>%
              regionalCV(init = 48))
system.time(adreno_gp_cv_models_4 <-
  adreno_monthly_quantity_gp_pre_cv19 %>%
    filter(regional_unit %in% complete_gp[301:length(complete_gp)]) %>%
              regionalCV(init = 48))
plan(sequential)

adreno_gp_cv_models <-
  bind_rows(adreno_gp_cv_models_1,
            adreno_gp_cv_models_2,
            adreno_gp_cv_models_3,
            adreno_gp_cv_models_4)

adreno_gp_cv_models %>%
  saveRDS("../data/adreno_gp_cv_models.rds")

adreno_gp_cv_models <- 
  read_rds("../data/adreno_gp_cv_models.rds")

adreno_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  ggplot(aes(x = MAPE)) +
  geom_histogram()

adreno_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  group_by(.model) %>% 
  count() %>% 
  arrange(desc(n))

adreno_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  ggplot(aes(x = reorder(.model, MAPE, mean), y = MAPE)) + # reorder by mean of y
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90))

```


* 

```{r gp-modelling-accuracy}
best_model_gp <- 
  adreno_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE)

best_model_gp %>% 
  left_join(select(gp, practice_id, npat, ngp), 
            by = c("regional_unit" = "practice_id")) %>% 
  select(-c(.model, .type)) %>% 
  DataExplorer::plot_correlation()

adreno_monthly_quantity_gp_pre_cv19 %>% 
  as_tibble() %>% 
  group_by(regional_unit) %>% 
  summarise(mean_quantity = mean(n))

best_model_gp %>% 
  left_join(adreno_monthly_quantity_gp_pre_cv19 %>% 
              as_tibble() %>% 
              group_by(regional_unit) %>% 
              summarise(mean_quantity = mean(n)), 
            by = c("regional_unit")) %>% 
  select(-c(.model, .type)) %>% 
  DataExplorer::plot_correlation()

```



```{r gp-practice-forecasts}
plan(cluster)
system.time(adreno_gp_fcsts <-
              adreno_monthly_quantity_gp_pre_cv19 %>%
              filter(regional_unit %in% complete_gp) %>%
              regionalJointFcsts())
plan(sequential)

adreno_gp_fcsts %>%
  saveRDS("../data/adreno_gp_fcsts.rds")

adreno_gp_fcsts <- 
  read_rds("../data/adreno_gp_fcsts.rds")

```

* 2755.011 seconds 2021-01-13

## Discrepancies

### By Health Board

```{r, health-board-discrepancies}
best_model_hb <- 
  adreno_hb_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE)

best_model_hb %>% 
  select(.model, regional_unit) %>% 
  inner_join(mutate(adreno_hb_fcsts,
                    datename = yearmonth(datename)), 
             by = c(".model", "regional_unit")) %>%
  left_join(mutate(select(adreno_monthly_quantity_hb, 
                          c(regional_unit, datename, n)), 
                   datename = yearmonth(datename)),
            by = c("datename", "regional_unit")) %>% 
  mutate(discrepancy = n - .mean,
         z_discrepancy = discrepancy/sd) %>% 
  ggplot(aes(y = discrepancy)) +
  geom_line(aes(x = datename, y = discrepancy, colour = as.factor(regional_unit)),
            alpha = .8, lty = 2) +
  geom_hline(aes(yintercept = 0), colour = "red") +
  theme(legend.position = "none")
```

### By GP Cluster

```{r, gp-cluster-discrepancies}
best_model_gp_cluster <- 
  adreno_gp_cluster_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE)

best_model_gp_cluster %>% 
  select(.model, regional_unit) %>% 
  inner_join(mutate(adreno_gp_cluster_fcsts,
                    datename = yearmonth(datename)), 
             by = c(".model", "regional_unit")) %>%
  left_join(mutate(select(adreno_monthly_quantity_cluster, 
                          c(regional_unit, datename, n)), 
                   datename = yearmonth(datename)),
            by = c("datename", "regional_unit")) %>% 
  mutate(discrepancy = n - .mean,
         z_discrepancy = discrepancy/sd) %>% 
  ggplot(aes(y = discrepancy)) +
  # geom_boxplot(aes(x = as.factor(datename))) +
  geom_line(aes(x = datename, y = discrepancy, colour = as.factor(regional_unit)),
            alpha = .8, lty = 2) +
  # scale_color_gradientn(colours = rainbow(100))+
  geom_hline(aes(yintercept = 0), colour = "red") +
  theme(legend.position = "none")
```

```{r, eval = FALSE}
best_model_gp_cluster %>% 
  select(.model, regional_unit) %>% 
  inner_join(mutate(adreno_gp_cluster_fcsts,
                    datename = yearmonth(datename)), 
             by = c(".model", "regional_unit")) %>%
  left_join(mutate(select(adreno_monthly_quantity_cluster, 
                          c(regional_unit, datename, n)), 
                   datename = yearmonth(datename)),
            by = c("datename", "regional_unit")) %>% 
  mutate(discrepancy = n - .mean,
         z_discrepancy = discrepancy/sd)  %>%
  select(discrepancy, regional_unit, datename) %>%
  pivot_wider(names_from = datename, values_from = discrepancy) %>% 
  ungroup() %>% 
  select(-regional_unit) %>% 
  estimate_profiles(1:6, models = c(1:3, 6)) %>% 
  compare_solutions(statistics = c("AIC", "BIC"))
```


### By GP Practice

```{r, gp-practice-discrepancies}
best_model_gp <- 
  adreno_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE)

best_model_gp %>% 
  ggplot(aes(x = MAPE)) + 
  geom_histogram()

best_model_gp %>% 
  group_by(if_else(MAPE < 50, TRUE, FALSE)) %>% 
  count()

median(best_model_gp$MAPE)

acc_filter_value <- 50
  
best_model_gp_discrep <- 
  best_model_gp %>% 
  filter(MAPE <= acc_filter_value) %>% 
  select(.model, regional_unit) %>% 
  inner_join(mutate(adreno_gp_fcsts,
                    datename = yearmonth(datename)), 
             by = c(".model", "regional_unit")) %>%
  left_join(mutate(select(adreno_monthly_quantity_gp, 
                          c(regional_unit, datename, n)), 
                   datename = yearmonth(datename)),
            by = c("datename", "regional_unit")) %>% 
  mutate(discrepancy = n - .mean,
         z_discrepancy = discrepancy/sd) 

best_model_gp_discrep %>% 
  ggplot(aes(y = discrepancy)) +
  geom_line(aes(x = datename, y = discrepancy, 
                colour = as.factor(regional_unit)),
            alpha = .8, lty = 2) +
  geom_hline(aes(yintercept = 0), colour = "red") +
  theme(legend.position = "none")

```


#### Latent profile analysis

```{r gp-lpa}
gp_lpa_fit <- 
  best_model_gp_discrep  %>%
  select(discrepancy, regional_unit, datename) %>%
  pivot_wider(names_from = datename, values_from = discrepancy) %>% 
  ungroup() %>% 
  select(-regional_unit) %>% 
  estimate_profiles(1:6, models = c(1:3, 6))

gp_lpa_fit %>% 
  compare_solutions(statistics = c("AIC", "BIC"))

gp_lpa_fit %>% 
  compare_solutions(statistics = c("AIC", "BIC")) %>% 
  .[[1]] %>% 
  ggplot(aes(x = Classes, y = BIC, group = Model, colour = as.factor(Model))) +
  geom_line()

gp_lpa_fit %>%
  plot_profiles(x = ., rawdata = FALSE)
```

#### mplus 

```{r, mplus-data-prep}
best_model_gp_discrep %>% 
  mutate(regional_unit = as.factor(regional_unit)) %>% 
  select(regional_unit, datename, discrepancy) %>% 
  filter(!is.na(discrepancy)) %>% # need to remove NA before pivoting to enable values_fill
  pivot_wider(names_from = datename, values_from = discrepancy, values_fill = -999) %>% 
  left_join(select(gp, c(practice_id, cluster)), by = c("regional_unit" = "practice_id")) %>% 
  mutate(regional_unit = as.factor(regional_unit),
         cluster = as.factor(cluster)) %>% 
  mutate(regional_unit = as.numeric(regional_unit),
         cluster = as.numeric(cluster)) %>% 
  select(cluster, regional_unit, everything()) %>% 
  write_csv(file = "../data/mplus/adreno_gp_discrep.csv", col_names = FALSE)

```



```{r, mplus-anlayses, eval=FALSE}
source("../r_scripts/functions/mplus_plotting.R")
# mplus_models <- MplusAutomation::readModels("../mplus_analyses/adreno_gp")

mplus_model_summaries <- 
  readModels("../mplus_analyses/adreno_gp", what = "summaries", quiet = TRUE)

best_mplus_model_summary <- 
  mplus_model_summaries %>% 
  flatten() %>% 
  map(2) %>% 
  bind_rows() %>% 
  filter(Estimator == "MLR" & AnalysisType == "mixture") %>% 
  arrange(BIC) %>% 
  slice(1)

best_mplus_model <- 
  readModels(paste0("../mplus_analyses/adreno_gp/", best_mplus_model_summary$Filename))

adreno_discrep_5_class_ml <- 
  readModels("../mplus_analyses/adreno_gp/adreno_discrep_5_class_ml.out")

best_mplus_model$class_counts

# mplus.view.plots("../mplus_analyses/adreno_gp/adreno_discrep_3_class_lgmm_ml.gh5")
mplus.plot.estimated_means("../mplus_analyses/adreno_gp/adreno_discrep_3_class_lgmm_ml.gh5")
```

#### kmeans

```{r, gp-kmeans}
gp_kmeans_data <- 
  best_model_gp_discrep %>%  
  mutate(regional_unit = as.factor(regional_unit)) %>% 
  select(regional_unit, datename, discrepancy) %>% 
  filter(!is.na(discrepancy)) %>% # need to remove NA before pivoting to enable values_fill
  pivot_wider(names_from = datename, values_from = discrepancy) %>% 
  as_tibble() %>% 
  na.omit()

1:6 %>% 
  map_dfr(~as.data.frame(kmeans(x = gp_kmeans_data[2:6], centers = .x, nstart = 25)$cluster), 
          .id = "n_clusters") %>% 
  mutate(regional_unit = rep(gp_kmeans_data$regional_unit, 6)) %>% 
  pivot_wider(names_from = "n_clusters", id_cols = regional_unit,
              values_from = "kmeans(x = gp_kmeans_data[2:6], centers = .x, nstart = 25)$cluster")

1:6 %>% 
  map_dfr(~as.data.frame(kmeans(x = gp_kmeans_data[2:6],
                                centers = .x, nstart = 25)$centers), 
          .id = "n_clusters") %>% 
  rownames_to_column(var = "cluster") %>% 
  mutate(cluster = 
           str_remove_all(cluster, 
                          pattern = DOT %R% DOT %R% DOT %R% 
                            one_or_more(DIGIT))) %>% 
  pivot_longer(cols = starts_with("2020 "), names_to = "datename") %>% 
  ggplot(aes(x = yearmonth(datename), y = value, colour = as.factor(cluster))) + 
  geom_line() +
  facet_wrap(~n_clusters)
  

```
#### Comparing methods

```{r, eval=FALSE}
mplus_assignment <- 
  read_table("../mplus_analyses/adreno_gp/adreno_discrep_5_class_ml_cprob.txt", col_names = FALSE, na = "*") %>% 
  na.omit() %>% 
  .$X17

kmeans_assignment <- 
  kmeans(x = gp_kmeans_data[2:6], centers = 5, nstart = 25)$cluster

lpa_assignment <- 
  gp_lpa_fit$model_1_class_5$model$classification

df <- bind_cols(mplus_assignment, kmeans_assignment, lpa_assignment)

df %>% 
  ggplot(aes(x = mplus_assignment, y = kmeans_assignment, 
             colour = as.factor(mplus_assignment)))+
  geom_jitter(aes(shape = as.factor(kmeans_assignment)), alpha = .5)

df %>% 
  ggplot(aes(x = mplus_assignment, y = lpa_assignment, 
             colour = as.factor(kmeans_assignment))) +
  geom_jitter(alpha = .5)

```

