---
title: "Exploring Hydroxychloroquine Sulfate"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(lubridate)
library(rstan) # needed to load prophet
library(prophet)

```

BNF code: 1001030C0

```{r prep-data}
con <- DBI::dbConnect(RSQLite::SQLite(), "../OneDrive/1_data/gpextract/db-gpextract.sqlite")
db.gpextract <- tbl(con, "gpextract")

chlor <- db.gpextract %>% 
  filter(bnfchem %in% "1001030C0") %>% 
  collect() %>% 
  mutate(datename = dmy(paste0("01-", datename))) # Add day component to date and convert to date-time object

chlor_monthly_count <- chlor %>% 
  group_by(datename) %>% 
  count()

chlor_monthly_count$datename %>% unique()

chlor_monthly_count_pre_cv19 <- chlor %>% 
  filter(datename < dmy("01-03-2020")) %>% 
  group_by(datename) %>% 
  count()
```


```{r chlor-monthly-ts-plot}
chlor_monthly_count %>% 
  ggplot(aes(x = datename, y = n)) +
  geom_line() +
  geom_vline(xintercept = dmy("23-March-2020"), colour = "red") # add line to mark the start of lockdown
```


```{r chlor-monthly-models}
# RW model
chlor_rw_model <-
  arima(as.ts(chlor_monthly_count_pre_cv19$n), order = c(0, 1, 0))
# 1st order MA model
chlor_ma1_model <-
  arima(as.ts(chlor_monthly_count_pre_cv19$n), order = c(0, 0, 1))

print(chlor_rw_model)

# Prophet model
chlor_prophet_model <- 
  prophet(df = chlor_monthly_count_pre_cv19 %>% 
            transmute(ds = datename, y = n)) # data in prophet format
future <- make_future_dataframe(chlor_prophet_model, periods = 5)
prophet_forecast <- predict(chlor_prophet_model, future)
```


```{r chlor-monthly-models-plots}
chlor_monthly_count %>% 
  ggplot(aes(x = datename, y = n)) +
  geom_line() +
  geom_ribbon(aes(ymin = c(rep(NA,50), 
                           (predict(chlor_rw_model, n.ahead = 5)$pred) - 
                             1.96*predict(chlor_rw_model, n.ahead = 5)$se),
                  ymax = c(rep(NA,50), 
                           (predict(chlor_rw_model, n.ahead = 5)$pred) + 
                             1.96*predict(chlor_rw_model, n.ahead = 5)$se)),
              alpha = .1, fill = "blue") +
  geom_ribbon(aes(ymin = c(rep(NA,50), prophet_forecast[51:55,]$yhat_lower),
                  ymax = c(rep(NA,50), prophet_forecast[51:55,]$yhat_upper)),
              alpha = .1, fill = "green") +
  geom_line(aes(y = c(chlor_monthly_count[1:50,]$n - chlor_rw_model$residuals, rep(NA, 5))),
            col = "blue", lty = 2) +
  geom_line(aes(y = c(chlor_monthly_count[1:50,]$n - chlor_ma1_model$residuals, rep(NA, 5))),
            col = "cyan", lty = 2) +
  geom_line(aes(y = c(prophet_forecast[1:50,]$yhat, rep(NA, 5))),
            col = "green", lty = 2) +
  geom_line(aes(y = c(rep(NA,50), predict(chlor_rw_model, n.ahead = 5)$pred)),
            col = "blue", lty = 3) +
  geom_line(aes(y = c(rep(NA,50), predict(chlor_ma1_model, n.ahead = 5)$pred)),
            col = "cyan", lty = 3) +
  geom_line(aes(y = c(rep(NA,50), prophet_forecast[51:55,]$yhat)),
            col = "green", lty = 3) +
  geom_vline(xintercept = dmy("23-March-2020"), colour = "red") # add line to mark the start of lockdown
```

Look at `fable` package and prohpet version too for forecasting