---
title: "Oral anticoagulants"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup}
## Packages
# devtools::install_github("https://github.com/w-hardy/serCymruTools")
library(tidyverse)
library(lubridate)
library(tsibble)
library(rstan) # needed to load prophet
library(prophet)
library(fable)
library(fable.prophet)
library(feasts)
library(furrr)
library(serCymruTools)

## Options
knitr::opts_chunk$set(cache = TRUE)
options(mc.cores = parallel::detectCores() - 1)
rstan_options(auto_write = TRUE)

## Seed
set.seed(32)


## Function

propRegional <- function(data, region, datename = datename, unit = Quantity, 
                         bnf){
  # Function to create tsibble object for a proportion of a drug by a given `unit` 
  # per `datename`
  # e.g. propRegional(oc, Locality, datename, Quantity) is the `Quantity`
  # per `datename` grouped by `Locality` from `oc`. `Quantity` is corrected for
  # the number of days in each month.
  region <- enquo(region)
  datename <- enquo(datename)
  unit <- enquo(unit)
  
  data %>%
    mutate(regional_unit = as_factor(set_names(!!region))) %>%
    group_by(!!datename, bnfchem, regional_unit) %>% 
    summarise(n = sum(!!unit)) %>% 
    mutate(n = 100 * n / sum(n),
           log_n = log(n)) %>% 
    filter(bnfchem == bnf) %>%
    ungroup() %>%
    as_tsibble(index = !!datename, key = regional_unit)
}

```

## Preparing data

```{r prep-data}
## Drugs of interest
oral_anticoagulants <- 
  c("0208020H0", "0208020Z0", "0208020X0", "0208020AA", "0208020W0", 
    "020802000", "0208020I0", "0208020N0", "0208020S0", "0208020Y0", 
    "0208020V0")
warf <- "0208020V0"


# ## Read from database
# con <- DBI::dbConnect(RSQLite::SQLite(), 
#                       "../OneDrive/1_data/gpextract/db-gpextract.sqlite")
# db.gpextract <- tbl(con, "gpextract")
# oac_p <- db.gpextract %>%
#   filter(bnfchem %in% oral_anticoagulants) %>%
#   collect() %>%
#   mutate(datename = dmy(paste0("28-", datename)))  # Add day component to date and convert to date-time object
# DBI::dbDisconnect(con)
# 
# ## Write to local file
# oac_p %>%
#   write_rds("../data/oral_anticoagulants.rds")

## Read from local file
gp <- read_rds("../OneDrive/2_interimdata/8_linkeddata/gp_agesex_qof_combined.rds") %>% 
  mutate(npat = N,
         N = NULL) %>% 
  filter(year == 2020) # Do something better. Is npat important for the proportion?

oac_p <- read_rds("../data/oral_anticoagulants.rds") 

## Sort into monthly count data
oac_p_monthly_count <- 
  oac_p %>% 
  group_by(datename, bnfchem) %>% 
  summarise(n = sum(Quantity)) %>% 
  mutate(n = 100 * n / sum(n), # make it a percentage rather than proportion
         log_n = log(n)) %>% 
  filter(bnfchem == warf) %>% 
  ungroup() %>%
  as_tsibble(index = datename)

oac_p_monthly_quantity_hb <- 
  right_join(oac_p, select(gp, c(practiceid, hboard)), 
             by = c("PracticeID" = "practiceid")) %>%
  propRegional(region = hboard, datename = datename, unit = Quantity,
               bnf = warf) 

oac_p_monthly_quantity_cluster <- 
  right_join(oac_p, select(gp, c(practiceid, cluster)), 
             by = c("PracticeID" = "practiceid")) %>%
  propRegional(cluster, datename, Quantity, bnf = warf)

oac_p_monthly_quantity_gp <- 
  propRegional(oac_p, PracticeID, datename, Quantity, bnf = warf)
  

## Sort into monthly count data pre-lockdown (2020-03-23)
oac_p_monthly_count_pre_cv19 <- 
  oac_p_monthly_count %>% 
  filter(datename < dmy("01-03-2020"))

oac_p_monthly_quantity_hb_pre_cv19 <- 
  oac_p_monthly_quantity_hb %>% 
    filter(datename < dmy("01-03-2020"))

oac_p_monthly_quantity_cluster_pre_cv19 <- 
  oac_p_monthly_quantity_cluster %>% 
    filter(datename < dmy("01-03-2020"))

oac_p_monthly_quantity_gp_pre_cv19 <- 
  oac_p_monthly_quantity_gp %>% 
    filter(datename < dmy("01-03-2020"))


```


## Overview

### 2016-2020 plot of all oac_p prescriptions 

```{r oac_p-monthly-ts-plot, fig.cap="Total quantity of combined oral anticoagulants prescribed per month."}
oac_p %>% 
  group_by(datename) %>% 
  summarise(n = sum(Quantity)) %>% 
  tsibble() %>% 
  autoplot(n) +
  geom_vline(xintercept = dmy("23-March-2020"), colour = "red") # add line to mark the start of lockdown
```

```{r oac-p-monthly-ts-plot, fig.cap="Total quantity of combined oral anticoagulants prescribed per month."}
oac_p_monthly_count %>% 
  select(datename, n) %>% 
  autoplot() +
  geom_vline(xintercept = dmy("23-March-2020"), colour = "red") # add line to mark the start of lockdown
```


### Seasonality

```{r oac_p-monthly-seasonality-plot}
df <- oac_p_monthly_count_pre_cv19 %>% 
  mutate(month = as.factor(month(datename, label = TRUE, abbr = TRUE)),
         year = as.factor(year(datename))) 

df2 <- df %>% 
  as_tibble() %>% 
  filter(year(datename) != 2020) %>% 
  group_by(month) %>% 
  summarise(n = mean(n))

df %>% 
  ggplot(aes(x = month, y = n, colour = year, group = year)) +
  geom_line() +
  geom_line(data = df2, aes(x = month, y = n, group = "Avg"), 
            colour = "red", lty = 2) +
  labs(caption = "Red dashed line is mean for 2016-2019")

```
* 


```{r}
oac_p_monthly_count_pre_cv19 %>% 
  mutate(datename = yearmonth(datename)) %>% 
  gg_subseries(y = n, period = "year")
```


### Autocorrelation

```{r}
tseries::adf.test(oac_p_monthly_count$n)
urca::ur.df(oac_p_monthly_count$n)
```


```{r}
oac_p_monthly_count_pre_cv19 %>%
  mutate(datename = yearmonth(datename)) %>% 
  ACF(n, lag_max = 24) %>% autoplot()
```

* Autocorrelation greatest at 2 and 12

```{r}
oac_p_monthly_count_pre_cv19$n %>%
  pacf(lag.max = 24)
```


## Modelling

### By Health Board

```{r, health-board-modelling}
# system.time(oac_p_hb_cv_models <-
#   regionalCV(data = oac_p_monthly_quantity_hb_pre_cv19))
# 
# oac_p_hb_cv_models %>%
#   write_rds("../data/oac_p_hb_cv_models.rds")

oac_p_hb_cv_models <- 
  read_rds("../data/oac_p_hb_cv_models.rds")

oac_p_hb_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  ggplot(aes(x = MAPE)) +
  geom_histogram()

oac_p_hb_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  group_by(.model) %>% 
  count() %>% 
  arrange(desc(n))

oac_p_hb_cv_models %>% 
  group_by(regional_unit) %>% 
  ggplot(aes(x = reorder(.model, MAPE, mean), y = MAPE)) + # reorder by mean of y
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90))
```

* 724.044 seconds with multisession prophetModels()

```{r}
# system.time(oac_p_hb_fcsts <- regionalJointFcsts(oac_p_monthly_quantity_hb_pre_cv19))
# 
# oac_p_hb_fcsts %>%
#   write_rds("../data/oac_p_hb_fcsts.rds")

oac_p_hb_fcsts <- 
  read_rds("../data/oac_p_hb_fcsts.rds")
```

* 194.071 seconds 2020-12-10


### By GP Cluster

```{r, gp-cluster-modelling}
# system.time(oac_p_gp_cluster_cv_models <-
#   regionalCV(data = oac_p_monthly_quantity_cluster_pre_cv19))
# 
# oac_p_gp_cluster_cv_models %>%
#   write_rds("../data/oac_p_gp_cluster_cv_models.rds")

oac_p_gp_cluster_cv_models <- 
  read_rds("../data/oac_p_gp_cluster_cv_models.rds")

oac_p_gp_cluster_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  ggplot(aes(x = MAPE)) +
  geom_histogram()

oac_p_gp_cluster_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  group_by(.model) %>% 
  count() %>% 
  arrange(desc(n))

oac_p_gp_cluster_cv_models %>% 
  group_by(regional_unit) %>% 
  ggplot(aes(x = reorder(.model, MAPE, mean), y = MAPE)) + # reorder by mean of y
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90))


```

* 5514.279 seconds

```{r}
# plan(multisession)
# system.time(oac_p_gp_cluster_fcsts <- regionalJointFcsts(oac_p_monthly_quantity_cluster_pre_cv19))
# plan(sequential)
# 
# oac_p_gp_cluster_fcsts %>%
#   write_rds("../data/oac_p_gp_cluster_fcsts.rds")

oac_p_gp_cluster_fcsts <- 
  read_rds("../data/oac_p_gp_cluster_fcsts.rds")
```

* 1266.126 seconds 2020-12-10


### By Practice

```{r, gp-practice-modelling}
regionalCV <- function(data, cv_dist = 6, init = 36, step = 1){

  # CV accuracy for fableModels() and prophetModels()

  regions <- unique(data$regional_unit) # Get unique regional_units for map()
  
  fableModels <- function(data){
  if(!is_tsibble(data)){data <- as_tsibble(data, index = datename)}

  data %>%
    mutate(datename = yearmonth(datename)) %>%
    model(trend_model1 = TSLM(log(n) ~ trend()),#time series linear model
          trend_model2 = TSLM(log(n) ~ trend() + season("year")),
          ets1 = ETS(log(n) ~ trend()),
          ets2 = ETS(log(n) ~ trend() + season("A")),
          ets3 = ETS(log(n) ~ trend() + season("M")),
          arima = ARIMA(log(n), stepwise = FALSE, approximation = FALSE),
          neur_net = NNETAR(log(n)),
          #fasster = FASSTER(n ~ season("1 year") + trend(1) + fourier(12)),
          comb1 = combination_model(TSLM(log(n) ~ trend()),
                                    ETS(log(n) ~ trend())),
          comb2 = combination_model(TSLM(log(n) ~ trend() + season("year")),
                                    ETS(log(n) ~ trend() + season("A"))),
          stl_dcmp1 = decomposition_model(STL(log(n) ~ trend(),
                                              iterations = 1000,
                                              robust = TRUE),
                                          SNAIVE(season_adjust)),
          stl_dcmp2 = decomposition_model(STL(log(n) ~ trend() + season(),
                                              iterations = 1000,
                                              robust = TRUE),
                                          SNAIVE(season_adjust)),
          s_naive = SNAIVE(log(n)))# %>%
    #as_tibble() # map_dfr() doesn't work on tsibble objects
  }
  
  prophetModels <- function(data){
  if(!is_tsibble(data)){data <- as_tsibble(data, index = datename)}

  oc_prophet_model1 <-
    fable.prophet::prophet(log(n) ~ growth("linear", n_changepoints = 0) +
                             season("year", type = "additive") +
                             holiday(holidays))
  oc_prophet_model2 <-
    fable.prophet::prophet(log(n) ~ growth("linear", n_changepoints = 0) +
                             season("year", type = "multiplicative") +
                             holiday(holidays))
  oc_prophet_model3 <-
    fable.prophet::prophet(log(n) ~ growth("linear") +
                             season("year", type = "additive") +
                             holiday(holidays))
  oc_prophet_model4 <-
    fable.prophet::prophet(log(n) ~ growth("linear") +
                             season("year", type = "multiplicative") +
                             holiday(holidays))
  oc_prophet_model5 <-
    fable.prophet::prophet(log(n) ~ season("year", type = "additive") +
                             holiday(holidays))
  oc_prophet_model6 <-
    fable.prophet::prophet(log(n) ~ season("year", type = "multiplicative") +
                             holiday(holidays))
  oc_prophet_model7 <-
    fable.prophet::prophet(log(n) ~ holiday(holidays))
  oc_prophet_model8 <-
    fable.prophet::prophet(log(n))

  data %>%
    mutate(datename = yearmonth(datename)) %>%
    model(oc_prophet_model1, oc_prophet_model2, oc_prophet_model3,
          oc_prophet_model4, oc_prophet_model5, oc_prophet_model6,
          oc_prophet_model7, oc_prophet_model8, .safely = TRUE)
}


holidays <-
  bind_rows(tibble(holiday = "christmas",
                   ds = as.Date(c("2016-12-25", "2017-12-25", "2018-12-25",
                                  "2019-12-25", "2020-12-25", "2021-12-25")),
                   lower_window = -1,
                   upper_window = 1),

            tibble(holiday = "easter", # Sunday
                   ds = as.Date(c("2016-03-27", "2017-04-16", "2018-04-01",
                                  "2019-04-21", "2020-04-12", "2021-04-04")),
                   lower_window = -2,
                   upper_window = 1))


  fableCV <- function(data){ # Return CV model accuracy for fableModels()
    data_test <-
      data %>%
      mutate(datename = yearmonth(datename))

    data_tr <-
      data %>%
      select(regional_unit, datename, n) %>%
      mutate(datename = yearmonth(datename)) %>%
      fill_gaps() %>%
      slice(1:(n()-cv_dist), .preserve = TRUE) %>%
      stretch_tsibble(.init = init, .step = step)

    data_tr %>%
      fableModels() %>%
      forecast(h = cv_dist) %>%
      accuracy(data_test)

  }

  prophetCV <- function(data){# Return CV model accuracy for prophetModels()
    data_test <-
      data %>%
      mutate(datename = yearmonth(datename))

    data_tr <-
      data %>%
      select(regional_unit, datename, n) %>%
      mutate(datename = yearmonth(datename)) %>%
      fill_gaps() %>%
      slice(1:(n()-cv_dist), .preserve = TRUE) %>%
      stretch_tsibble(.init = init, .step = step)

    data_tr %>%
      prophetModels() %>%
      forecast(h = cv_dist) %>%
      accuracy(data_test)
  }

  plan(cluster) # Set up parallel processing to decrease computation time
  # Prophet models won't run with plan(multisession) so need to be run
  # sequentially. Is it worth trying to write this in Python and pass it back
  # to R?

    # Probably worth trying the prophet::cross_validation() method. If it
    # returns RMSE and is faster it will be useful.
  prophet_fits <-
    future_map_dfr(.x =  regions,
            .f = ~prophetCV(data = filter(data, regional_unit == .x)),
            .options = furrr_options(seed = TRUE))
  message("prophetModels() complete")

  # Fable models will run using plan(multisession), but need to be run as below
  # with `furrr_options(seed = TRUE)` otherwise improper random numbers are
  # generated
  fable_fits <-
    future_map_dfr(.x =  regions,
                   .f = ~fableCV(data = filter(data, regional_unit == .x)),
                   .options = furrr_options(seed = TRUE))
  plan(sequential) # Close the multiprocess function to prevent memory leakage
  message("fableModels() complete")

  bind_rows(fable_fits, prophet_fits) %>%
    group_by(regional_unit) %>%
    arrange(RMSE, MAE)
}


incomplete_gp <- oac_p_monthly_quantity_gp_pre_cv19 %>% 
    as_tibble() %>% 
    group_by(regional_unit) %>% 
    count() %>% 
    filter(n < 50) %>% 
    .$regional_unit %>% 
    unique()

system.time(oac_p_gp_cv_models <-
  oac_p_monthly_quantity_gp_pre_cv19 %>%
    filter(!regional_unit %in% incomplete_gp) %>%
              regionalCV())

oac_p_gp_cv_models %>%
  write_rds("../data/oac_p_gp_cv_models.rds")

oac_p_gp_cv_models <- 
  read_rds("../data/oac_p_gp_cv_models.rds")

oac_p_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  ggplot(aes(x = MAPE)) +
  geom_histogram()

oac_p_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  group_by(.model) %>% 
  count() %>% 
  arrange(desc(n))

oac_p_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  ggplot(aes(x = reorder(.model, MAPE, mean), y = MAPE)) + # reorder by mean of y
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90))

```


* 2.195e+04 seconds 2020-12-07
* 25547.266 seconds 2020-12-09


```{r}
# regionalJointFcsts <- function (data, h = "5 months", keep_fits = FALSE) 
# {
#   if (!is.logical(keep_fits)) {
#     stop("`keep_fits` must be of type logical")
#   }
#   regions <- unique(data$regional_unit)
#   
#   cl <- parallel::makeCluster(8)
#   plan(cluster, workers = cl)
#   
#   fable_fcst <- 
#     future_map_dfr(.x = regions, 
#                    .f = ~fableModels(filter(data, 
#                                             regional_unit == .x)) %>% 
#                      forecast(h = h) %>% as_tibble(), 
#                    .options = furrr_options(seed = TRUE))
#   
#   
#   message("fable fits complete, step 1/4")
#   message("fable forecasts complete, step 2/4")
# 
#   prophet_fcst <- 
#     future_map_dfr(.x = regions, 
#                    .f = ~prophetModels(filter(data, 
#                                             regional_unit == .x)) %>% 
#                      forecast(h = h) %>% as_tibble(), 
#                    .options = furrr_options(seed = TRUE))
#   message("prophet fits complete, step 3/4")
#   message("prophet forecasts complete, step 4/4")
#   
#   parallel::stopCluster(cl)
#   plan(sequential)
#   joint_fcst <- dplyr::bind_rows(fable_fcst, prophet_fcst) %>% 
#     dplyr::mutate(lb_95 = quantile(n, 0.025), lb_80 = quantile(n, 
#       0.1), med = median(n), ub_80 = quantile(n, 0.9), 
#       ub_95 = quantile(n, 0.975), sd = distributional::variance(n)^2, 
#       dist = n, n = NULL)
#       return(list(forecasts = joint_fcst))
# }

system.time(oac_p_gp_fcsts <-
              oac_p_monthly_quantity_gp_pre_cv19 %>%
              filter(!regional_unit %in% incomplete_gp) %>%
              regionalJointFcsts())

oac_p_gp_fcsts %>%
  write_rds("../data/oac_p_gp_fcsts.rds")

oac_p_gp_fcsts <- 
  read_rds("../data/oac_p_gp_fcsts.rds")
```

* 2020-12-18 2694 secs

## Discrepancies

### By Health Board

```{r, health-board-discrepancies}
best_model_hb <- 
  oac_p_hb_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE)

best_model_hb %>% 
  select(.model, regional_unit) %>% 
  inner_join(mutate(oac_p_hb_fcsts,
                    datename = yearmonth(datename)), 
             by = c(".model", "regional_unit")) %>%
  left_join(mutate(select(oac_p_monthly_quantity_hb, 
                          c(regional_unit, datename, n)), 
                   datename = yearmonth(datename)),
            by = c("datename", "regional_unit")) %>% 
  mutate(discrepancy = n - .mean,
         z_discrepancy = discrepancy/sd) %>% 
  ggplot(aes(y = discrepancy)) +
  geom_line(aes(x = datename, y = discrepancy, colour = as.factor(regional_unit)),
            alpha = .8, lty = 2) +
  geom_hline(aes(yintercept = 0), colour = "red") +
  theme(legend.position = "none")
```

### By GP Cluster

```{r, gp-cluster-discrepancies}
best_model_gp_cluster <- 
  oac_p_gp_cluster_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE)

best_model_gp_cluster %>% 
  select(.model, regional_unit) %>% 
  inner_join(mutate(oac_p_gp_cluster_fcsts,
                    datename = yearmonth(datename)), 
             by = c(".model", "regional_unit")) %>%
  left_join(mutate(select(oac_p_monthly_quantity_cluster, 
                          c(regional_unit, datename, n)), 
                   datename = yearmonth(datename)),
            by = c("datename", "regional_unit")) %>% 
  mutate(discrepancy = n - .mean,
         z_discrepancy = discrepancy/sd) %>% 
  ggplot(aes(y = discrepancy)) +
  # geom_boxplot(aes(x = as.factor(datename))) +
  geom_line(aes(x = datename, y = discrepancy, colour = as.factor(regional_unit)),
            alpha = .8, lty = 2) +
  # scale_color_gradientn(colours = rainbow(100))+
  geom_hline(aes(yintercept = 0), colour = "red") +
  theme(legend.position = "none")
```

```{r, eval = FALSE}
# lcmm::

```


```{r}
best_model_gp_cluster %>% 
  select(.model, regional_unit) %>% 
  inner_join(mutate(oac_p_gp_cluster_fcsts,
                    datename = yearmonth(datename)), 
             by = c(".model", "regional_unit")) %>%
  left_join(mutate(select(oac_p_monthly_quantity_cluster, 
                          c(regional_unit, datename, n)), 
                   datename = yearmonth(datename)),
            by = c("datename", "regional_unit")) %>% 
  mutate(discrepancy = (n - .mean), # Why are the numbers so small?
         regional_unit = as.factor(regional_unit)) %>% 
  select(regional_unit, datename, discrepancy) %>% 
  pivot_wider(names_from = datename, values_from = discrepancy) %>% 
  mutate(regional_unit = as.numeric(regional_unit)) %>% 
  write_csv(file = "../data/mplus/oac_cluster_discrep.csv", col_names = FALSE)
```

### By GP Practice

```{r, gp-practice-discrepancies}
best_model_gp <- 
  oac_p_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE)

best_model_gp %>% 
  select(.model, regional_unit) %>% 
  inner_join(mutate(oac_p_gp_fcsts,
                    datename = yearmonth(datename)), 
             by = c(".model", "regional_unit")) %>%
  left_join(mutate(select(oac_p_monthly_quantity_gp, 
                          c(regional_unit, datename, n)), 
                   datename = yearmonth(datename)),
            by = c("datename", "regional_unit")) %>% 
  mutate(discrepancy = n - .mean,
         z_discrepancy = discrepancy/sd) %>% 
  ggplot(aes(y = discrepancy)) +
  # geom_boxplot(aes(x = as.factor(datename))) +
  geom_line(aes(x = datename, y = discrepancy, colour = as.factor(regional_unit)),
            alpha = .8, lty = 2) +
  geom_hline(aes(yintercept = 0), colour = "red") +
  theme(legend.position = "none")


```



```{r, eval = FALSE}
best_model_gp %>% 
  select(.model, regional_unit) %>% 
  inner_join(mutate(oac_p_gp_fcsts,
                    datename = yearmonth(datename)), 
             by = c(".model", "regional_unit")) %>%
  left_join(mutate(select(oac_p_monthly_quantity_gp, 
                          c(regional_unit, datename, n)), 
                   datename = yearmonth(datename)),
            by = c("datename", "regional_unit")) %>% 
  mutate(discrepancy = 1000000*(n - .mean), # Why are the numbers so small?
         regional_unit = as.factor(regional_unit)) %>% 
  select(regional_unit, datename, discrepancy) %>% 
  pivot_wider(names_from = datename, values_from = discrepancy) %>% 
  mutate(regional_unit = as.numeric(regional_unit)) %>% 
  na.omit() %>% .[2:5] %>% min()
  write_csv(file = "../data/mplus/oac_gp_discrep.csv", col_names = FALSE)
```

```{r, eval = FALSE}
source("../r_scripts/functions/mplus_plotting.R")
mplus.view.plots("../mplus_analyses/oac_discrep_3_class_bayes.gh5")
mplus.plot.estimated_means("../mplus_analyses/oac_discrep_3_class_bayes.gh5")
```

