---
title: "gp_dimensionality"
author: "Will A. S. Hardy"
date: "26/02/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lavaan)

set.seed(32)
knitr::opts_chunk$set(echo = TRUE)
gp <- 
  read_rds("../OneDrive/2_interimdata/8_linkeddata/gp_agesex_qof_combined.rds") %>% 
  mutate(npat = N,
         N = NULL,
         practice_id = as_factor(practiceid),
         dispensing = as_factor(dispensing),
         hboard = as_factor(str_remove_all(hboard, "W110000")),
         cluster = as_factor(cluster)) %>% 
  ungroup() %>% 
  filter(year == 2020) %>% 
  select(-c(practiceid, postcode, easting, northing, lsoacode, year)) %>% 
  janitor::clean_names() %>%
  mutate(across(chd:flu, .fns = ~.x*100))

gp1 <- 
  gp %>% 
  mutate(block = randomizr::block_ra(blocks = as.character(gp$cluster), prob = .4)) %>% # Try cluster_ra() and then all practices from a cluster will be in one dataset. Could also then stratify (block) by heatlh board
  filter(block == 0)

gp2 <- 
  filter(gp, !practice_id %in% gp1$practice_id) %>% 
  mutate(across(chd:flu, scale))
```


```{r, inspect-data}
gp1 %>%
  select(chd:flu) %>% 
  psych::describe() %>% 
  arrange(sd)

gp1 %>%
  select(chd:flu) %>% 
  DataExplorer::plot_histogram()

gp %>%
  select(chd:flu) %>% 
  DataExplorer::plot_correlation()


gp1 %>% 
  group_by(cluster) %>%
  summarise(across(chd:flu, sd))

gp1 %>% 
  group_by(county) %>%
  summarise(across(chd:flu, sd))

gp1 %>% 
  group_by(hboard) %>%
  summarise(across(chd:flu, sd))

gp2 %>% 
  select(chd:flu) %>% 
  DataExplorer::plot_histogram()

```


## EFA

```{r}
df <- select(gp1, chd:flu, -epi)
psych::fa.parallel(df)

three_fac <- psych::fa(df, nfactors = 3, rotate = "varimax")
four_fac <- psych::fa(df, nfactors = 4, rotate = "varimax")
five_fac <- psych::fa(df, nfactors = 5, rotate = "varimax")
print(three_fac$loadings, cutoff = .3)
print(four_fac$loadings, cutoff = .3)
```

* Retain items with single loading >.5 and not cross-loadings >.3

```{r, three-fac-cfa-1}
one_level_three_fac_cfa1 <- 
'
  f1 =~ copd + diab + hyp + obi + can
  f2 =~ dem + hf + ost + pal + str + af
  f3 =~ lrn + men
'

three_fac_fit1 <- sem(model = one_level_three_fac_cfa1, data = gp1, estimator = "MLR")

summary(three_fac_fit1, fit.measures = TRUE, standardized = TRUE)

modindices(three_fac_fit1, sort. = TRUE)

```


```{r, four-fac-cfa-1}
one_level_four_fac_cfa1 <- 
'
  f1 =~ str + af + flu
  f2 =~ obi + ast + copd
  f3 =~ lrn + men
  f4 =~ ost + pal + dem
'

four_fac_fit1 <- sem(model = one_level_four_fac_cfa1, data = gp1, estimator = "MLR")

summary(four_fac_fit1, fit.measures = TRUE, standardized = TRUE)

modindices(four_fac_fit1, sort. = TRUE)

```


```{r}
summary(three_fac)
summary(four_fac)
summary(five_fac)
```

## CFA

### Cardiovascular factor

```{r, cfa-cardiovascular}
cv_one_level_cfa1 <- 
  '
  cardio      =~ af + chd + hf + str
  '

cv_two_level_cfa1 <- 
'
  level: 1
  cardio      =~ af + chd + hf + str

  level: 2 # Saturated correlation matrix
  
  af    ~~ af + chd + hf + str
  chd   ~~ chd + hf + str
  hf    ~~ hf + str
  str   ~~ str
'


cv_one_level_fit1 <- cfa(model = cv_one_level_cfa1, data = gp1, estimator = "MLR")
cv_two_level_fit1 <- cfa(model = cv_two_level_cfa1, data = gp1, cluster = "cluster", estimator = "MLR")

summary(cv_one_level_fit1, fit.measures = TRUE, standardized = TRUE)
modindices(cv_one_level_fit1, sort. = TRUE)

summary(cv_two_level_fit1, fit.measures = TRUE, standardized = TRUE)
modindices(cv_two_level_fit1, sort. = TRUE)

lavInspect(cv_two_level_fit1, "icc")
```


### Lifestyle factor

```{r, cfa-lifestyle}
life_one_level_cfa1 <- 
  '
  life      =~ diab + copd + obi + can
  '

life_two_level_cfa1 <- 
'
  level: 1
  life      =~ diab + copd + obi + can

  level: 2 # Saturated correlation matrix
  
  diab  ~~ diab + copd + obi + can
  copd  ~~ copd + obi + can
  obi   ~~ obi + can
  can   ~~ can
'


life_one_level_fit1 <- cfa(model = life_one_level_cfa1, data = gp1, estimator = "MLR")
life_two_level_fit1 <- cfa(model = life_two_level_cfa1, data = gp1, cluster = "cluster", estimator = "MLR")

summary(life_one_level_fit1, fit.measures = TRUE, standardized = TRUE)
modindices(life_one_level_fit1, sort. = TRUE)

summary(life_two_level_fit1, fit.measures = TRUE, standardized = TRUE)
modindices(life_two_level_fit1, sort. = TRUE)

lavInspect(life_two_level_fit1, "icc")
```


```{r, cfa-age}
age_two_level_cfa1 <- 
'
  level: 1
  age      =~ dem + rar + pal + ost 

  level: 2 # Saturated correlation matrix
  dem ~~ dem + rar + pal + ost 
  rar ~~ rar + pal + ost 
  pal ~~ pal + ost 
  ost ~~ ost
'


age_two_level_fit1 <- cfa(model = age_two_level_cfa1, data = gp1, cluster = "cluster", estimator = "MLR")

summary(age_two_level_fit1, fit.measures = TRUE, standardized = TRUE)
modindices(age_two_level_fit1, sort. = TRUE)

lavInspect(age_two_level_fit1, "icc")

# rar ns and low loading
age_two_level_cfa2 <- 
'
  level: 1
  age  =~ dem + ost + pal

  level: 2 # Saturated correlation matrix
  dem ~~ dem + ost + pal
  ost ~~ ost + pal
  pal ~~ pal
'


age_two_level_fit2 <- cfa(model = age_two_level_cfa2, data = gp1, cluster = "cluster", estimator = "MLR")

summary(age_two_level_fit2, fit.measures = TRUE, standardized = TRUE)
modindices(age_two_level_fit2, sort. = TRUE)

lavInspect(age_two_level_fit2, "icc")


```

* Too few df to calculate model fit

### Cardiovascular and lifestyle

```{r, cfa-cv-lifestyle}
cv_life_two_level_cfa1 <- 
'
  level: 1
  cardio    =~ af + chd + hf + str
  life      =~ diab + copd + obi + can

  level: 2 # Saturated correlation matrix
  af    ~~ af + chd + hf + str + diab + copd + obi + can
  chd   ~~ chd + hf + str + diab + copd + obi + can
  hf    ~~ hf + str + diab + copd + obi + can
  str   ~~ str + diab + copd + obi + can
  diab  ~~ diab + copd + obi + can
  copd  ~~ copd + obi + can
  obi   ~~ obi + can
  can   ~~ can
'

cv_life_two_level_fit1 <- cfa(model = cv_life_two_level_cfa1, data = gp1, cluster = "cluster", estimator = "MLR")

summary(cv_life_two_level_fit1, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)
modindices(cv_life_two_level_fit1, sort. = TRUE)

lavInspect(cv_life_two_level_fit1, "icc")

# Removed cancer as had highest mi (46.793)
cv_life_two_level_cfa2 <- 
'
  level: 1
  cardio    =~ af + chd + hf + str
  life      =~ diab + copd + obi

  level: 2 # Saturated correlation matrix
  af    ~~ af + chd + hf + str + diab + copd + obi
  chd   ~~ chd + hf + str + diab + copd + obi
  hf    ~~ hf + str + diab + copd + obi
  str   ~~ str + diab + copd + obi
  diab  ~~ diab + copd + obi
  copd  ~~ copd + obi
  obi   ~~ obi
'

cv_life_two_level_fit2 <- cfa(model = cv_life_two_level_cfa2, data = gp1, cluster = "cluster", estimator = "MLR")
summary(cv_life_two_level_fit2, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)
modindices(cv_life_two_level_fit2, sort. = TRUE)

# Removed diab 
cv_life_two_level_cfa3 <- 
'
  level: 1
  cardio    =~ af + chd + hf + str
  life      =~ copd + obi

  level: 2 # Saturated correlation matrix
  af    ~~ af + chd + hf + str + copd + obi
  chd   ~~ chd + hf + str + copd + obi
  hf    ~~ hf + str + copd + obi
  str   ~~ str + copd + obi
  copd  ~~ copd + obi
  obi   ~~ obi
'

cv_life_two_level_fit3 <- cfa(model = cv_life_two_level_cfa3, data = gp1, cluster = "cluster", estimator = "MLR")
summary(cv_life_two_level_fit3, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)
modindices(cv_life_two_level_fit3, sort. = TRUE)


## test final model on unseen data
cv_life_two_level_test <- 
  cfa(model = cv_life_two_level_cfa3, data = gp2, cluster = "cluster", estimator = "MLR")
summary(cv_life_two_level_test, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)


```


### Cardiovascular, lifestyle, and age

```{r, cfa-cv-lifestyle-age}
cv_life_age_two_level_cfa1 <- 
'
  level: 1
  cardio    =~ af + chd + hf + str
  life      =~ copd + obi
  age       =~ dem + ost

  level: 2 # Saturated correlation matrix
  af    ~~ af + chd + hf + str + copd + obi + dem + ost
  chd   ~~ chd + hf + str + copd + obi + dem + ost
  hf    ~~ hf + str + copd + obi + dem + ost
  str   ~~ str + copd + obi + dem + ost
  copd  ~~ copd + obi + dem + ost
  obi   ~~ obi + dem + ost
  dem   ~~ dem + ost
  ost   ~~ ost
'

cv_life_age_two_level_fit1 <- 
  cfa(model = cv_life_age_two_level_cfa1, data = gp1, cluster = "cluster", estimator = "MLR")

summary(cv_life_age_two_level_fit1, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)
modindices(cv_life_age_two_level_fit1, sort. = TRUE)

lavInspect(cv_life_age_two_level_fit1, "icc")
lavInspect(cv_life_age_two_level_fit1, "cov.lv")

## test final model on unseen data
cv_life_two_level_test <- 
  cfa(model = cv_life_age_two_level_cfa1, data = gp2, cluster = "cluster", estimator = "MLR")
summary(cv_life_two_level_test, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)

```

### Cardiovascular, lifestyle, and age

```{r, cfa-cv-lifestyle-age-men}
cv_life_age_cog_two_level_cfa1 <- 
'
  level: 1
  cardio    =~ af + chd + hf + str
  life      =~ copd + obi
  age       =~ dem + ost
  cog       =~ lrn + men

  level: 2 # Saturated correlation matrix
  af    ~~ af + chd + hf + str + copd + obi + dem + ost + lrn + men
  chd   ~~ chd + hf + str + copd + obi + dem + ost + lrn + men
  hf    ~~ hf + str + copd + obi + dem + ost + lrn + men
  str   ~~ str + copd + obi + dem + ost + lrn + men
  copd  ~~ copd + obi + dem + ost + lrn + men
  obi   ~~ obi + dem + ost + lrn + men
  dem   ~~ dem + ost + lrn + men
  ost   ~~ ost + lrn + men
  lrn   ~~ lrn + men
  men   ~~ men
'

cv_life_age_cog_two_level_fit1 <- 
  cfa(model = cv_life_age_cog_two_level_cfa1, data = gp1, cluster = "cluster", estimator = "MLR")

summary(cv_life_age_cog_two_level_fit1, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)
modindices(cv_life_age_cog_two_level_fit1, sort. = TRUE)

lavInspect(cv_life_age_cog_two_level_fit1, "icc")
lavInspect(cv_life_age_cog_two_level_fit1, "cov.lv")

## test final model on unseen data
cv_life_age_cog_two_level_test <- 
  cfa(model = cv_life_age_cog_two_level_cfa1, data = gp2, cluster = "cluster", estimator = "MLR")
summary(cv_life_age_cog_two_level_test, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)

```


## Factor scores

```{r}
m1 <- cfa(model = cv_life_age_two_level_cfa1, data = gp, cluster = "cluster", estimator = "MLR")
summary(m1,fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)

new_df <- bind_cols(gp, as_tibble(predict(m1)))
summary(lm(flu ~ cardio + life + age, data = new_df))
car::vif(lm(flu ~ cardio + life, data = new_df))
```



## PCA


```{r}
psych::fa.parallel(select(gp1, chd:flu))
five_fac <- psych::fa(select(gp1, chd:flu), nfactors = 3, rotate = "varimax")
print(five_fac$loadings, cutoff = .2)

dis_pca <- psych::principal(select(gp1, chd:flu), nfactors = 3, scores = TRUE)
plot(dis_pca$values)
dis_pca$rotation
dis_pca_scores <- bind_cols(practice_id = gp1$practice_id, dis_pca$scores)

# 2d plot
x <- dis_pca$loadings[,1]
y <- dis_pca$loadings[,2]
z <- dis_pca$loadings[,3]

pca_plot_df <- bind_cols(dis = names(x), x = x, y = y, z = z)

ggplot(aes(x = x, y = y), data = pca_plot_df) +
  geom_text(aes(label = dis))

ggplot(aes(x = x, y = z), data = pca_plot_df) +
  geom_text(aes(label = dis))

# 3d plot
plotly::plot_ly(x=x, y=y, z=z, data = pca_plot_df,
                type="scatter3d", mode="text", text = ~dis)
```

