---
title: "R Notebook"
output: html_notebook
---

```{r, include=FALSE}
# Packages ####
library(tidyverse)
library(lubridate)
library(tsibble)
library(rstan) # needed to load prophet
library(prophet)
library(fable)
library(fable.prophet)
library(feasts)
library(furrr)
library(knitr)

# Data ####
oc <- read_rds("../data/oral_contraceptives.rds")
oac <- read_rds("../data/oral_anticoagulants.rds")
```

## 2019 vs 2020

### Oral anticoagulants
```{r}
an_ch_oc_mar <- 
  oc %>% 
  group_by(datename) %>% 
  summarise(n = sum(Quantity)) %>% 
  filter(str_detect(datename, "-03-") & year(datename) %in% c(2019:2020))

print("march")
100*an_ch_oc_mar$n[2] / an_ch_oc_mar$n[1]

an_ch_oc_apr <- 
  oc %>% 
  group_by(datename) %>% 
  summarise(n = sum(Quantity)) %>% 
  filter(str_detect(datename, "-04-") & year(datename) %in% c(2019:2020))

print("april")
100*an_ch_oc_apr$n[2] / an_ch_oc_apr$n[1]

```


### Oral anticoagulants
```{r}
an_ch_oac_mar <- 
  oac %>% 
  group_by(datename) %>% 
  summarise(n = sum(Quantity)) %>% 
  filter(str_detect(datename, "-03-") & year(datename) %in% c(2019:2020))

print("march")
100*an_ch_oac_mar$n[2] / an_ch_oac_mar$n[1]

an_ch_oac_apr <- 
  oac %>% 
  group_by(datename) %>% 
  summarise(n = sum(Quantity)) %>% 
  filter(str_detect(datename, "-04-") & year(datename) %in% c(2019:2020))

print("april")
100*an_ch_oac_apr$n[2] / an_ch_oac_apr$n[1]

```