---
title: "Respiratory oacsteroids"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup}
## Packages
devtools::install_github("https://github.com/w-hardy/serCymruTools")
library(tidyverse)
library(lubridate)
library(tsibble)
library(rstan) # needed to load prophet
library(prophet)
library(fable)
library(fable.prophet)
library(feasts)
library(furrr)
library(rebus)
library(MplusAutomation)
library(tidyLPA)
library(serCymruTools)

## Options
knitr::opts_chunk$set(cache = TRUE)
options(mc.cores = parallel::detectCores() - 1)
rstan_options(auto_write = TRUE)


## Seed
set.seed(32)

```

## Preparing data

```{r oac-data}
gp <- 
  read_rds("../OneDrive/2_interimdata/8_linkeddata/gp_agesex_qof_combined.rds") %>% 
  mutate(npat = N,
         N = NULL,
         practice_id = as_factor(practiceid)) %>% 
  ungroup() %>% 
  janitor::clean_names() %>% 
  select(practice_id, year, npat)

oac <- 
  read_rds("../data/presdata_updates_040121/presc_wales_OAC.rds") %>% 
  janitor::clean_names() %>% 
  mutate(datename = yearmonth(dmy(paste0("28-", datename))),
         practice_id = as_factor(practice_id))

warf <- "0208020V0"

## All data sorted into monthly summary
oac_monthly_prop <- 
  oac %>% 
  group_by(datename, bnfchem) %>% 
  summarise(n = sum(quantity)) %>% 
  mutate(n = 100 * n / sum(n)) %>%  # make it a percentage rather than proportion
  filter(bnfchem == warf) %>% 
  ungroup() %>%
  as_tsibble(index = datename)

## Monthly summary by GP
oac_monthly_prop_gp <- 
  oac %>% 
  group_by(practice_id, datename, bnfchem) %>% 
  summarise(sum_n = sum(quantity), .groups = "drop_last") %>% 
  mutate(p_war = 100 * sum_n / sum(sum_n),
         sum_oac = sum(sum_n)) %>% 
  filter(bnfchem == as_name(warf)) %>% 
  ungroup() %>% 
  transmute(regional_unit = as.factor(practice_id),
            datename = datename,
            n = p_war) %>%
  ungroup() %>%
  as_tsibble(index = datename, key = regional_unit) %>% 
  fill_gaps() 


oac_monthly_prop_gp_pre_cv19 <- 
  oac_monthly_prop_gp %>% 
  filter(datename < yearmonth("2020 March"))

oac_monthly_prop_gp_pre_cv19 <- 
  oac_monthly_prop_gp_pre_cv19 %>% 
  as_tibble() %>% 
  pivot_wider(id_cols = regional_unit, names_from = datename,
              values_from = n, values_fill = NA) %>% 
  pivot_longer(cols = `2015 Jan`:`2020 Feb`, 
               names_to = "datename", values_to = "n", 
               values_drop_na = FALSE) %>% 
  mutate(datename = yearmonth(datename)) %>% 
  as_tsibble(index = datename, key = regional_unit) %>% 
  group_by(regional_unit) %>% 
  model(mean = MEAN(n)) %>% 
  interpolate(oac_monthly_prop_gp_pre_cv19) %>% 
  filter(!regional_unit %in% # Remove those with <62 months data
           (oac_monthly_prop_gp_pre_cv19 %>% 
              as_tibble %>% 
              ungroup() %>% 
              group_by(regional_unit) %>% 
              count() %>% 
              filter(n < 62) %>% 
              .$regional_unit) &
           !regional_unit %in% # Remove bottom 10% GPs by total oac volume 
           (oac %>% 
              group_by(practice_id) %>% 
              summarise(tot_quant = sum(quantity)) %>% 
              arrange(tot_quant) %>% 
              slice_tail(prop = .1))) 
```


```{r, eval = FALSE}
oac_monthly_prop_gp_pre_cv19 %>% 
  autoplot() +
  theme(legend.position = "none")
```


## Modelling


```{r, oac-gp-practice-modelling}
plan(cluster)
system.time(oac_gp_cv_models <-
  oac_monthly_prop_gp_pre_cv19 %>%
                  regionalCVBound(init = 48, step = 3))
plan(sequential)

oac_gp_cv_models %>%
  saveRDS("../data/oac_gp_cv_models.rds")

oac_gp_cv_models <- 
  read_rds("../data/oac_gp_cv_models.rds")

oac_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  ggplot(aes(x = MAPE)) +
  geom_histogram() +
  xlim(0,100)

oac_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  group_by(.model) %>% 
  count() %>% 
  arrange(desc(n))

oac_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  ggplot(aes(x = reorder(.model, MAPE, mean), y = MAPE)) + # reorder by mean of y
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90)) +
  coord_cartesian(ylim = c(0,100))

```


```{r oac-gp-modelling-accuracy}
best_model_gp <- 
  oac_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE)

best_mape_over_50 <- 
  best_model_gp %>% 
  filter(MAPE > 50)

```

* `r nrow(best_mape_over_50)` GPs excluded as MAPE >50%

```{r oac-gp-practice-forecasts}
plan(cluster)
system.time(oac_gp_fcsts <-
              oac_monthly_prop_gp_pre_cv19 %>%
              regionalJointFcstsBound(h = "6 months"))
plan(sequential)

oac_gp_fcsts %>%
  saveRDS("../data/oac_gp_fcsts.rds")

oac_gp_fcsts <- 
  read_rds("../data/oac_gp_fcsts.rds")

```


## Discrepancies

```{r, oac-gp-practice-discrepancies}
best_model_gp <- 
  oac_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  arrange(RMSE, MAE) %>% 
  slice(1, .preserve = TRUE) %>% 
  filter(MAPE < 50)

best_model_gp %>% 
  ggplot(aes(x = MAPE)) + 
  geom_histogram()

best_model_gp_discrep <- 
  best_model_gp %>% 
  select(.model, regional_unit) %>% 
  inner_join(mutate(oac_gp_fcsts,
                    datename = yearmonth(datename)), 
             by = c(".model", "regional_unit")) %>%
  left_join(mutate(select(oac_monthly_prop_gp, 
                          c(regional_unit, datename, n)), 
                   datename = yearmonth(datename)),
            by = c("datename", "regional_unit")) %>% 
  mutate(discrepancy = n - .mean) %>% 
  ungroup()

best_model_gp_discrep %>% 
  saveRDS("../data/differences/oac_discreps.rds")

best_model_gp_discrep %>% 
  ggplot(aes(y = discrepancy)) +
  geom_line(aes(x = datename, y = discrepancy, 
                colour = as.factor(regional_unit)),
            alpha = .8, lty = 2) +
  geom_hline(aes(yintercept = 0), colour = "red") +
  theme(legend.position = "none")

```
