---
title: "Respiratory corticosteroids"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup}
## Packages
devtools::install_github("https://github.com/w-hardy/serCymruTools")
library(tidyverse)
library(lubridate)
library(tsibble)
library(rstan) # needed to load prophet
library(prophet)
library(fable)
library(fable.prophet)
library(feasts)
library(furrr)
library(rebus)
library(MplusAutomation)
library(tidyLPA)
library(serCymruTools)

## Options
knitr::opts_chunk$set(cache = TRUE)
options(mc.cores = parallel::detectCores() - 1)
rstan_options(auto_write = TRUE)


## Seed
set.seed(32)

```

## Preparing data

```{r cortico-data}
gp <- 
  read_rds("../../OneDrive/2_interimdata/8_linkeddata/gp_agesex_qof_combined.rds") %>% 
  mutate(npat = N,
         N = NULL,
         practice_id = as_factor(practiceid)) %>% 
  ungroup() %>% 
  janitor::clean_names() %>% 
  select(practice_id, year, npat)

cortico <- 
  read_rds("../../data/presdata_updates_040121/presc_wales_cortico-resp.rds") %>% 
  janitor::clean_names() %>% 
  mutate(datename = dmy(paste0("28-", datename)),
         practice_id = as_factor(practiceid))

## All data sorted into monthly summary
cortico_monthly_count <- 
  cortico %>% 
  group_by(datename) %>% 
  summarise(n = sum(quantity)) %>% 
  mutate(datename = yearmonth(datename),
         n = case_when(str_detect(datename, pattern = "Jan") ~ n/31,
                       str_detect(datename, pattern = "Feb") ~ n/28.25,
                       str_detect(datename, pattern = "Mar") ~ n/31,
                       str_detect(datename, pattern = "Apr") ~ n/30,
                       str_detect(datename, pattern = "May") ~ n/31,
                       str_detect(datename, pattern = "Jun") ~ n/30,
                       str_detect(datename, pattern = "Jul") ~ n/31,
                       str_detect(datename, pattern = "Aug") ~ n/31,
                       str_detect(datename, pattern = "Sep") ~ n/30,
                       str_detect(datename, pattern = "Oct") ~ n/31,
                       str_detect(datename, pattern = "Nov") ~ n/30,
                       str_detect(datename, pattern = "Dec") ~ n/31)) %>% 
  ungroup() %>% 
  as_tsibble(index = datename)

## Monthly summary by GP
cortico_monthly_quantity_gp <- 
  countRegional(cortico, practice_id, datename, quantity) %>% 
  mutate(year = year(datename)) %>%
  as_tibble() %>% 
  inner_join(gp, 
            by = c("regional_unit" = "practice_id", "year")) %>% 
  mutate(n = 1000*n/npat,
         datename = yearmonth(datename),
         regional_unit = as_factor(regional_unit)) %>% 
  select(-c(npat, year)) %>% 
  as_tsibble(index = datename, key = regional_unit) %>% 
  fill_gaps()

## Identify GPs with missing data 
gp_missing <- 
  cortico_monthly_quantity_gp %>% 
  as_tibble() %>% 
  pivot_wider(id_cols = regional_unit, names_from = datename,
              values_from = n, values_fill = NA) %>% 
  rowwise() %>% 
  mutate(across(.cols = `2015 Jan`:`2020 Aug`, .fns = is.na)) %>% 
  group_by(regional_unit) %>% 
  summarise(miss_non_covid = sum(c_across(`2015 Jan`:`2020 Feb`)),
            miss_covid = sum(c_across(`2020 Mar`:`2020 Aug`))) %>% 
  filter(miss_covid > 0 | miss_non_covid > 0) %>% 
  mutate(miss_10_non_covid = if_else(miss_non_covid > 60/10, TRUE, FALSE))

gp_miss_remove <- 
  gp_missing %>% 
  filter(miss_covid > 0 | miss_10_non_covid == TRUE) %>% 
  .$regional_unit

## Remove GPs with missing data in covid months and >10% of non-covid months
cortico_monthly_quantity_gp <- 
  cortico_monthly_quantity_gp %>% 
  filter(!regional_unit %in% gp_miss_remove)

## Sort into monthly count data pre-lockdown (March 2020) as training data
cortico_monthly_count_pre_cv19 <- 
  cortico_monthly_count %>% 
  filter(datename < yearmonth(dmy("01-01-2020"))) 

cortico_monthly_quantity_gp_pre_cv19 <- 
  cortico_monthly_quantity_gp %>% 
  filter(datename < yearmonth(dmy("01-01-2020"))) 

## Replace missing values in training data
cortico_monthly_count_pre_cv19 <- 
  cortico_monthly_count_pre_cv19 %>% 
  model(arima = ARIMA(n)) %>%
  interpolate(cortico_monthly_count_pre_cv19)

cortico_monthly_quantity_gp_pre_cv19 <- 
  cortico_monthly_quantity_gp_pre_cv19%>% 
  group_by(regional_unit) %>% 
  model(arima = ARIMA(n)) %>% 
  interpolate(cortico_monthly_quantity_gp_pre_cv19)

```

```{r}
gp_missing %>% 
  knitr::kable()
```


* `r length(gp_miss_remove)` GPs removed as they had missing data in the COVID months (Mar-Aug 2020) or >10% missing data pre-covid


## Modelling

```{r, cortico-gp-practice-modelling}
plan(cluster)
system.time(cortico_gp_cv_models <-
  cortico_monthly_quantity_gp_pre_cv19 %>%
                  regionalCV(init = 36, step = 3))
plan(sequential)

cortico_gp_cv_models %>%
  saveRDS("../../data/cortico_gp_cv_models.rds")

cortico_gp_cv_models <- 
  read_rds("../../data/cortico_gp_cv_models.rds")

cortico_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  rankModels() %>% 
  slice(1, .preserve = TRUE) %>% 
  ggplot(aes(x = MAPE)) +
  geom_histogram() +
  xlim(0,100)

cortico_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  rankModels() %>% 
  slice(1, .preserve = TRUE) %>% 
  group_by(.model) %>% 
  count() %>% 
  arrange(desc(n))

cortico_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  ggplot(aes(x = reorder(.model, MAPE, mean), y = MAPE)) + # reorder by mean of y
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90)) +
  coord_cartesian(ylim = c(0,100))

```


```{r cortico-gp-modelling-accuracy}
best_model_gp <- 
  cortico_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  rankModels() %>% 
  slice(1, .preserve = TRUE)

best_mape_over_50 <- 
  best_model_gp %>% 
  filter(MAPE > 50)

```

* `r nrow(best_mape_over_50)` GPs excluded as MAPE >50%

```{r cortico-gp-practice-forecasts}
plan(cluster)
system.time(cortico_gp_fcsts <-
              cortico_monthly_quantity_gp_pre_cv19 %>%
              filter(!regional_unit %in% best_mape_over_50$regional_unit) %>%
              regionalJointFcsts(h = "8 months"))
plan(sequential)

cortico_gp_fcsts %>%
  saveRDS("../../data/cortico_gp_fcsts.rds")

cortico_gp_fcsts <- 
  read_rds("../../data/cortico_gp_fcsts.rds")

```


## Discrepancies

```{r, cortico-gp-practice-discrepancies}
best_model_gp <- 
  cortico_gp_cv_models %>% 
  group_by(regional_unit) %>% 
  rankModels() %>% 
  slice(1, .preserve = TRUE) %>% 
  filter(MAPE < 50)

best_model_gp %>% 
  ggplot(aes(x = MAPE)) + 
  geom_histogram()

best_model_gp_discrep <- 
  best_model_gp %>% 
  select(.model, regional_unit) %>% 
  inner_join(mutate(cortico_gp_fcsts,
                    datename = yearmonth(datename)), 
             by = c(".model", "regional_unit")) %>%
  left_join(mutate(select(cortico_monthly_quantity_gp, 
                          c(regional_unit, datename, n)), 
                   datename = yearmonth(datename)),
            by = c("datename", "regional_unit")) %>% 
  mutate(discrepancy = n - med, # observed - forecast
         prop = n / med) %>% 
  ungroup()

best_model_gp_discrep %>% 
  ggplot(aes(y = discrepancy)) +
  geom_line(aes(x = datename, y = discrepancy, 
                colour = as.factor(regional_unit)),
            alpha = .8, lty = 2) +
  geom_hline(aes(yintercept = 0), colour = "red") +
  theme(legend.position = "none")

best_model_gp_discrep %>% 
  ggplot(aes(y = prop)) +
  geom_line(aes(x = datename, y = prop, 
                colour = as.factor(regional_unit)),
            alpha = .8, lty = 2) +
  geom_hline(aes(yintercept = 0), colour = "red") +
  theme(legend.position = "none")


cortico_monthly_quantity_gp %>% 
  filter(regional_unit %in%
           (best_model_gp_discrep %>%
           filter(prop < .25) %>%
           .$regional_unit %>%
           unique())) %>%
  autoplot()

gp %>% 
    filter(practice_id %in% 
           (best_model_gp_discrep %>% 
           filter(prop <.25) %>% 
           .$regional_unit %>% 
           unique()))

best_model_gp_discrep %>% 
  saveRDS("../../data/differences/cortico_discreps.rds")
```
