---
title: "All prescribing"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup}
## Packages
devtools::install_github("https://github.com/w-hardy/serCymruTools")
library(tidyverse)
library(lubridate)
library(tsibble)
library(rstan) # needed to load prophet
library(prophet)
library(fable)
library(fable.prophet)
library(feasts)
library(furrr)
library(rebus)
library(MplusAutomation)
library(tidyLPA)
library(serCymruTools)

## Options
knitr::opts_chunk$set(cache = TRUE)
options(mc.cores = parallel::detectCores() - 1)
rstan_options(auto_write = TRUE)


## Seed
set.seed(32)

```

## Preparing data

```{r all-prescribing-data}
gp <- 
  read_rds("../../OneDrive/2_interimdata/8_linkeddata/gp_agesex_qof_combined.rds") %>% 
  mutate(npat = N,
         N = NULL,
         practice_id = as_factor(practiceid)) %>% 
  ungroup() %>% 
  janitor::clean_names() %>% 
  select(practice_id, year, npat)

all_prescribing <- 
  read_csv("../../data/all_prescribing.csv", col_names = c("n", "datename")) %>% 
  mutate(datename = dmy(paste(28, datename, sep = "-")),
         datename = yearmonth(datename),
         regional_unit = factor("all")) %>% 
  as_tsibble(index = datename)

## Sort into monthly count data pre-lockdown (March 2020) as training data
all_prescribing_pre_cv19 <- 
  all_prescribing %>% 
  filter(datename < yearmonth(dmy("01-01-2020"))) 

```


## Modelling

```{r, all-prescribing-practice-modelling}
plan(cluster)

all_prescribing_fable_models <- 
  all_prescribing_pre_cv19 %>% 
  mutate(datename = yearmonth(datename)) %>%
  fill_gaps() %>%
  slice(1:(n()-8), .preserve = TRUE) %>%
  stretch_tsibble(.init = 36, .step = 3) %>%
  fableModels() 

all_prescribing_fable_forecasts <- 
  all_prescribing_fable_models %>%
  forecast(h = 8)

all_prescribing_fable_fits <- 
  all_prescribing_fable_forecasts %>% 
  accuracy(all_prescribing_pre_cv19, list(RMSE = RMSE, MAE = MAE, MAPE = MAPE,
                           rmse_skill = skill_score(RMSE),
                           crps_skill = skill_score(CRPS), ACF1 =ACF1,
                           winkler = winkler_score))

all_prescribing_prophet_fits <- 
  all_prescribing_pre_cv19 %>%
  mutate(datename = yearmonth(datename)) %>%
  fill_gaps() %>%
  slice(1:(n()-8), .preserve = TRUE) %>%
  stretch_tsibble(.init = 36, .step = 3) %>%
  prophetModels() %>%
  forecast(h = 8) %>%
  accuracy(all_prescribing_pre_cv19, list(RMSE = RMSE, MAE = MAE, MAPE = MAPE,
                           rmse_skill = skill_score(RMSE),
                           crps_skill = skill_score(CRPS), ACF1 =ACF1,
                           winkler = winkler_score))

all_prescribing_combined_fits <- 
  bind_rows(all_prescribing_fable_fits, all_prescribing_prophet_fits) %>%
  rankModels()
plan(sequential)


all_prescribing_cv_models <-
  all_prescribing_combined_fits

all_prescribing_cv_models %>%
  saveRDS("../../data/all_prescribing_cv_models.rds")

all_prescribing_cv_models <- 
  read_rds("../../data/all_prescribing_cv_models.rds")

all_prescribing_cv_models %>% 
  rankModels() %>% 
  slice(1, .preserve = TRUE) %>% 
  ggplot(aes(x = MAPE)) +
  geom_histogram()

all_prescribing_cv_models %>% 
  rankModels() %>% 
  slice(1, .preserve = TRUE) %>% 
  group_by(.model) %>% 
  count() %>% 
  arrange(desc(n))

all_prescribing_cv_models %>% 
  ggplot(aes(x = 1, y = MAPE)) + # reorder by mean of y
  geom_boxplot() +
  geom_jitter() +
  theme(axis.text.x = element_text(angle = 90)) 

```


```{r all-prescribing-modelling-accuracy}
best_model <- 
  all_prescribing_cv_models %>% 
  rankModels() %>% 
  slice(1, .preserve = TRUE)
```


```{r all-prescribing-practice-forecasts}
plan(cluster)
all_prescribing_fcsts <-
  all_prescribing_pre_cv19 %>%
  regionalJointFcsts(h = "8 months")
plan(sequential)

all_prescribing_fcsts %>%
  saveRDS("../../data/all_prescribing_fcsts.rds")

all_prescribing_fcsts <- 
  read_rds("../../data/all_prescribing_fcsts.rds")

```


## Discrepancies

```{r, all-prescribing-practice-discrepancies}
best_model %>% 
  ggplot(aes(x = MAPE)) + 
  geom_histogram()

best_model_discrep <- 
  best_model %>% 
  select(.model) %>% 
  inner_join(mutate(all_prescribing_fcsts,
                    datename = yearmonth(datename)), 
             by = c(".model")) %>%
  left_join(mutate(select(all_prescribing, 
                          c(regional_unit, datename, n)), 
                   datename = yearmonth(datename)),
            by = c("datename")) %>% 
  mutate(discrepancy = n - med, # observed - forecast
         prop = n / med) %>% 
  ungroup()

best_model_discrep %>% 
  ggplot(aes(y = discrepancy)) +
  geom_line(aes(x = datename, y = discrepancy, 
                colour = as.factor(regional_unit)),
            alpha = .8, lty = 2) +
  geom_hline(aes(yintercept = 0), colour = "red") +
  theme(legend.position = "none")

best_model_discrep %>% 
  ggplot(aes(y = prop)) +
  geom_line(aes(x = datename, y = prop, 
                colour = as.factor(regional_unit)),
            alpha = .8, lty = 2) +
  geom_hline(aes(yintercept = 0), colour = "red") +
  theme(legend.position = "none")


best_model_discrep %>% 
  transmute(datename = datename,
            n = med,
            type = "forecast") %>% 
  bind_rows(mutate(all_prescribing, type = "observed")) %>% 
  as_tsibble(index = datename, key = type) %>% 
  autoplot()


best_model_discrep %>% 
  saveRDS("../../data/differences/all_prescribing_discreps.rds")

fable_forecasts %>% 
  filter(.model == best_model$.model) %>% 
  ggplot(aes(x = datename)) +
  geom_line(aes(y = median(n))) +
  geom_line(aes(y = n, col = "observed"), data = all_prescribing) +
  geom_line(aes(y = med, col = "forecast"), data = best_model_discrep)

augment(fable_models) %>% 
  as_tibble() %>% 
  # filter(.model == "comb3") %>% 
  ggplot(aes(x = datename)) +
  geom_line(aes(y = n, colour = "Data")) +
  geom_line(aes(y = .fitted, colour = "Fitted", lty = as.factor(.id))) +
  facet_wrap(~.model)

```
